# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.AllowedOutput do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :Value
  ]

  @type t :: %__MODULE__{
    :ID => String.t,
    :Value => String.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.AllowedOutput do
  def decode(value, _options) do
    value
  end
end

