# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.ApplicationStatusRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Date,
    :Description,
    :Status
  ]

  @type t :: %__MODULE__{
    :Date => DateTime.t,
    :Description => String.t | nil,
    :Status => String.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.ApplicationStatusRequest do
  def decode(value, _options) do
    value
  end
end
