# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.ApplicationCommonData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Objective",
    :"ProfessionalSummary",
    :"DesiredEmployment",
    :"DesiredContracts",
    :"DesiredSalary",
    :"DesiredBenefits",
    :"DesiredLocations",
    :"RelocationPreferences",
    :"RemoteWorking",
    :"JobShift",
    :"OriginLinks"
  ]

  @type t :: %__MODULE__{
    :"Objective" => inda_hr.Model.BaseEmploymentsValueModelStrictStr.t | nil,
    :"ProfessionalSummary" => inda_hr.Model.BaseEmploymentsValueModelStrictStr.t | nil,
    :"DesiredEmployment" => inda_hr.Model.ResumeEmployment.t | nil,
    :"DesiredContracts" => [inda_hr.Model.ResumeContract.t] | nil,
    :"DesiredSalary" => inda_hr.Model.ResumeSalary.t | nil,
    :"DesiredBenefits" => [inda_hr.Model.ResumeBenefit.t] | nil,
    :"DesiredLocations" => [inda_hr.Model.BaseLocationsLocation.t] | nil,
    :"RelocationPreferences" => inda_hr.Model.RelocationPreferences.t | nil,
    :"RemoteWorking" => inda_hr.Model.JobAdRemoteWorking.t | nil,
    :"JobShift" => inda_hr.Model.JobShift.t | nil,
    :"OriginLinks" => [inda_hr.Model.JobadLinkLink.t] | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.ApplicationCommonData do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Objective", :struct, inda_hr.Model.BaseEmploymentsValueModelStrictStr, options)
    |> deserialize(:"ProfessionalSummary", :struct, inda_hr.Model.BaseEmploymentsValueModelStrictStr, options)
    |> deserialize(:"DesiredEmployment", :struct, inda_hr.Model.ResumeEmployment, options)
    |> deserialize(:"DesiredContracts", :list, inda_hr.Model.ResumeContract, options)
    |> deserialize(:"DesiredSalary", :struct, inda_hr.Model.ResumeSalary, options)
    |> deserialize(:"DesiredBenefits", :list, inda_hr.Model.ResumeBenefit, options)
    |> deserialize(:"DesiredLocations", :list, inda_hr.Model.BaseLocationsLocation, options)
    |> deserialize(:"RelocationPreferences", :struct, inda_hr.Model.RelocationPreferences, options)
    |> deserialize(:"RemoteWorking", :struct, inda_hr.Model.JobAdRemoteWorking, options)
    |> deserialize(:"JobShift", :struct, inda_hr.Model.JobShift, options)
    |> deserialize(:"OriginLinks", :list, inda_hr.Model.JobadLinkLink, options)
  end
end

