# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.Award do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Title,
    :Description,
    :Year,
    :Awarder
  ]

  @type t :: %__MODULE__{
    :Title => IndaHr.Model.Title.t | nil,
    :Description => IndaHr.Model.Description.t | nil,
    :Year => IndaHr.Model.DateTime.t | nil,
    :Awarder => IndaHr.Model.Organization.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.Award do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Title, :struct, IndaHr.Model.Title, options)
    |> deserialize(:Description, :struct, IndaHr.Model.Description, options)
    |> deserialize(:Awarder, :struct, IndaHr.Model.Organization, options)
  end
end
