# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.BaseResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Count",
    :"Prices",
    :"Detail"
  ]

  @type t :: %__MODULE__{
    :"Count" => integer(),
    :"Prices" => %{optional(String.t) => float()} | nil,
    :"Detail" => [inda_hr.Model.HistoryDetail.t] | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.BaseResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Detail", :list, inda_hr.Model.HistoryDetail, options)
  end
end

