# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.BaseResumeMatchingEvidenceQuery do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ResumeIDs
  ]

  @type t :: %__MODULE__{
    :ResumeIDs => [String.t]
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.BaseResumeMatchingEvidenceQuery do
  def decode(value, _options) do
    value
  end
end
