# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.BaseJobAdSearchQuery do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Application",
    :"JobAd"
  ]

  @type t :: %__MODULE__{
    :"Application" => inda_hr.Model.QueryFilters.t | nil,
    :"JobAd" => inda_hr.Model.QueryFilters.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.BaseJobAdSearchQuery do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Application", :struct, inda_hr.Model.QueryFilters, options)
    |> deserialize(:"JobAd", :struct, inda_hr.Model.QueryFilters, options)
  end
end

