# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.BaseApplicationRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Data,
    :HiringDetails
  ]

  @type t :: %__MODULE__{
    :Data => IndaHr.Model.ApplicationCommonData.t | nil,
    :HiringDetails => IndaHr.Model.HiringDetails.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.BaseApplicationRequest do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Data, :struct, IndaHr.Model.ApplicationCommonData, options)
    |> deserialize(:HiringDetails, :struct, IndaHr.Model.HiringDetails, options)
  end
end
