# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.BinaryItemResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :File,
    :FileExt,
    :Filename,
    :ID
  ]

  @type t :: %__MODULE__{
    :File => String.t,
    :FileExt => String.t,
    :Filename => String.t | nil,
    :ID => String.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.BinaryItemResponse do
  def decode(value, _options) do
    value
  end
end

