# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.BroaderLevelSkill do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :URI,
    :Label
  ]

  @type t :: %__MODULE__{
    :URI => String.t | nil,
    :Label => String.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.BroaderLevelSkill do
  def decode(value, _options) do
    value
  end
end
