# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.CacheDeletion do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Deleted",
    :"SearchID"
  ]

  @type t :: %__MODULE__{
    :"Deleted" => boolean(),
    :"SearchID" => String.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.CacheDeletion do
  def decode(value, _options) do
    value
  end
end

