# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.CefrLevels do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Overall,
    :Writing,
    :Reading,
    :Speaking,
    :Listening,
    :SpokenInteraction,
    :SpokenProduction
  ]

  @type t :: %__MODULE__{
    :Overall => String.t | nil,
    :Writing => String.t | nil,
    :Reading => String.t | nil,
    :Speaking => String.t | nil,
    :Listening => String.t | nil,
    :SpokenInteraction => String.t | nil,
    :SpokenProduction => String.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.CefrLevels do
  def decode(value, _options) do
    value
  end
end

