# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.Certification do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :CertificationName,
    :Description,
    :FirstIssuedDate,
    :IssuingAuthority,
    :URL
  ]

  @type t :: %__MODULE__{
    :CertificationName => IndaHr.Model.BaseModelsName.t | nil,
    :Description => IndaHr.Model.Description.t | nil,
    :FirstIssuedDate => IndaHr.Model.DateTime.t | nil,
    :IssuingAuthority => IndaHr.Model.Organization.t | nil,
    :URL => IndaHr.Model.ResumeLinkUrl.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.Certification do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:CertificationName, :struct, IndaHr.Model.BaseModelsName, options)
    |> deserialize(:Description, :struct, IndaHr.Model.Description, options)
    |> deserialize(:IssuingAuthority, :struct, IndaHr.Model.Organization, options)
    |> deserialize(:URL, :struct, IndaHr.Model.ResumeLinkUrl, options)
  end
end
