# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.Check do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Status",
    :"Message"
  ]

  @type t :: %__MODULE__{
    :"Status" => String.t,
    :"Message" => String.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.Check do
  def decode(value, _options) do
    value
  end
end

