# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.ClassificationMappingIscoResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ISCOCode,
    :ISCOOccupation,
    :"MappingO*NET",
    :MappingESCO,
    :MappingISTAT
  ]

  @type t :: %__MODULE__{
    :ISCOCode => String.t,
    :ISCOOccupation => String.t | nil,
    :"MappingO*NET" => [IndaHr.Model.OnetMapping.t] | nil,
    :MappingESCO => [IndaHr.Model.EscoMapping.t] | nil,
    :MappingISTAT => [IndaHr.Model.IstatMapping.t] | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.ClassificationMappingIscoResponse do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"MappingO*NET", :list, IndaHr.Model.OnetMapping, options)
    |> deserialize(:MappingESCO, :list, IndaHr.Model.EscoMapping, options)
    |> deserialize(:MappingISTAT, :list, IndaHr.Model.IstatMapping, options)
  end
end
