# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.CompanyAutocompleteResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Term,
    :Companies
  ]

  @type t :: %__MODULE__{
    :Term => String.t,
    :Companies => [IndaHr.Model.CompanyAutocomplete.t]
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.CompanyAutocompleteResponse do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Companies, :list, IndaHr.Model.CompanyAutocomplete, options)
  end
end
