# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.CompanyCommonData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Type,
    :Size,
    :Description,
    :Headquarters,
    :Branches,
    :Industries,
    :Specialties,
    :Founded,
    :Logo,
    :Link,
    :Products,
    :Services,
    :RelatedCompanies,
    :Name
  ]

  @type t :: %__MODULE__{
    :Type => inda_hr.Model.CompanyCommonType.t | nil,
    :Size => inda_hr.Model.Size.t | nil,
    :Description => inda_hr.Model.BaseLocationsValueModelStrictStr.t | nil,
    :Headquarters => [inda_hr.Model.Headquarter.t] | nil,
    :Branches => [inda_hr.Model.Branch.t] | nil,
    :Industries => [inda_hr.Model.CompanyCommonIndustry.t] | nil,
    :Specialties => [inda_hr.Model.BaseLocationsValueModelStrictStr.t] | nil,
    :Founded => inda_hr.Model.FoundationYear.t | nil,
    :Logo => inda_hr.Model.JobadLinkLink.t | nil,
    :Link => inda_hr.Model.JobadLinkLink.t | nil,
    :Products => [inda_hr.Model.Asset.t] | nil,
    :Services => [inda_hr.Model.Asset.t] | nil,
    :RelatedCompanies => [inda_hr.Model.RelatedCompany.t] | nil,
    :Name => inda_hr.Model.BaseLocationsValueModelStrictStr.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.CompanyCommonData do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Type, :struct, inda_hr.Model.CompanyCommonType, options)
    |> deserialize(:Size, :struct, inda_hr.Model.Size, options)
    |> deserialize(:Description, :struct, inda_hr.Model.BaseLocationsValueModelStrictStr, options)
    |> deserialize(:Headquarters, :list, inda_hr.Model.Headquarter, options)
    |> deserialize(:Branches, :list, inda_hr.Model.Branch, options)
    |> deserialize(:Industries, :list, inda_hr.Model.CompanyCommonIndustry, options)
    |> deserialize(:Specialties, :list, inda_hr.Model.BaseLocationsValueModelStrictStr, options)
    |> deserialize(:Founded, :struct, inda_hr.Model.FoundationYear, options)
    |> deserialize(:Logo, :struct, inda_hr.Model.JobadLinkLink, options)
    |> deserialize(:Link, :struct, inda_hr.Model.JobadLinkLink, options)
    |> deserialize(:Products, :list, inda_hr.Model.Asset, options)
    |> deserialize(:Services, :list, inda_hr.Model.Asset, options)
    |> deserialize(:RelatedCompanies, :list, inda_hr.Model.RelatedCompany, options)
    |> deserialize(:Name, :struct, inda_hr.Model.BaseLocationsValueModelStrictStr, options)
  end
end

