# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.CompanyAutocomplete do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Name,
    :ID
  ]

  @type t :: %__MODULE__{
    :Name => IndaHr.Model.BaseLocationsValueModelStrictStr.t,
    :ID => String.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.CompanyAutocomplete do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Name, :struct, IndaHr.Model.BaseLocationsValueModelStrictStr, options)
  end
end
