# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.CompanyAutocompleteResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Term",
    :"Companies"
  ]

  @type t :: %__MODULE__{
    :"Term" => String.t,
    :"Companies" => [inda_hr.Model.CompanyAutocomplete.t]
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.CompanyAutocompleteResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Companies", :list, inda_hr.Model.CompanyAutocomplete, options)
  end
end

