# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.CountStats do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Sent,
    :Queued
  ]

  @type t :: %__MODULE__{
    :Sent => integer(),
    :Queued => integer()
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.CountStats do
  def decode(value, _options) do
    value
  end
end

