# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.CustomizedFields do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"DocType",
    :"Indexname",
    :"Successful",
    :"Errors"
  ]

  @type t :: %__MODULE__{
    :"DocType" => String.t | nil,
    :"Indexname" => String.t,
    :"Successful" => boolean(),
    :"Errors" => map()
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.CustomizedFields do
  def decode(value, _options) do
    value
  end
end

