# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.CustomField do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Field,
    :Type,
    :Params
  ]

  @type t :: %__MODULE__{
    :Field => String.t,
    :Type => String.t,
    :Params => map() | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.CustomField do
  def decode(value, _options) do
    value
  end
end
