# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.DocsImportItemRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Bucket,
    :Files,
    :Credentials
  ]

  @type t :: %__MODULE__{
    :Bucket => String.t,
    :Files => [inda_hr.Model.DocsBucketItem.t],
    :Credentials => inda_hr.Model.AwsCredentials.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.DocsImportItemRequest do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Files, :list, inda_hr.Model.DocsBucketItem, options)
    |> deserialize(:Credentials, :struct, inda_hr.Model.AwsCredentials, options)
  end
end

