# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.DocumentTextResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :PlainText,
    :Language,
    :Filename,
    :FileExt,
    :ID
  ]

  @type t :: %__MODULE__{
    :PlainText => String.t,
    :Language => String.t | nil,
    :Filename => String.t | nil,
    :FileExt => String.t | nil,
    :ID => String.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.DocumentTextResponse do
  def decode(value, _options) do
    value
  end
end
