# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.DocumentTextResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Language",
    :"Filename",
    :"FileExt",
    :"PlainText",
    :"ID"
  ]

  @type t :: %__MODULE__{
    :"Language" => String.t | nil,
    :"Filename" => String.t | nil,
    :"FileExt" => String.t | nil,
    :"PlainText" => String.t,
    :"ID" => String.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.DocumentTextResponse do
  def decode(value, _options) do
    value
  end
end

