# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.Education do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Title,
    :EducationLevelCode,
    :Fields
  ]

  @type t :: %__MODULE__{
    :Title => IndaHr.Model.EducationTitle.t,
    :EducationLevelCode => IndaHr.Model.JobadEducationEducationLevelCode.t | nil,
    :Fields => [IndaHr.Model.BaseBenefitsValueModelStrictStr.t] | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.Education do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Title, :struct, IndaHr.Model.EducationTitle, options)
    |> deserialize(:EducationLevelCode, :struct, IndaHr.Model.JobadEducationEducationLevelCode, options)
    |> deserialize(:Fields, :list, IndaHr.Model.BaseBenefitsValueModelStrictStr, options)
  end
end
