# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.EntityMapping do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ID
  ]

  @type t :: %__MODULE__{
    :ID => String.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.EntityMapping do
  def decode(value, _options) do
    value
  end
end
