# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.EscoSkillResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Hits,
    :ESCOClassification
  ]

  @type t :: %__MODULE__{
    :Hits => integer() | nil,
    :ESCOClassification => [inda_hr.Model.OptionalEscoSkillMatch.t] | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.EscoSkillResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ESCOClassification, :list, inda_hr.Model.OptionalEscoSkillMatch, options)
  end
end

