# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.EscoMapping do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ESCOCode,
    :ESCOOccupation
  ]

  @type t :: %__MODULE__{
    :ESCOCode => String.t | nil,
    :ESCOOccupation => String.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.EscoMapping do
  def decode(value, _options) do
    value
  end
end
