# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.EscoJobtitleResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Hits,
    :ESCOClassification
  ]

  @type t :: %__MODULE__{
    :Hits => integer() | nil,
    :ESCOClassification => [IndaHr.Model.OptionalEscoOccupationMatch.t] | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.EscoJobtitleResponse do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ESCOClassification, :list, IndaHr.Model.OptionalEscoOccupationMatch, options)
  end
end
