# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.Experience do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Duration,
    :Seniority
  ]

  @type t :: %__MODULE__{
    :Duration => IndaHr.Model.OptionalRequiredAndPreferredDurationRange.t | nil,
    :Seniority => IndaHr.Model.OptionalRequiredAndPreferredSeniorityValue.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.Experience do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Duration, :struct, IndaHr.Model.OptionalRequiredAndPreferredDurationRange, options)
    |> deserialize(:Seniority, :struct, IndaHr.Model.OptionalRequiredAndPreferredSeniorityValue, options)
  end
end
