# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.ExtendedStandardDataItem do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Code,
    :Value,
    :Language,
    :Label
  ]

  @type t :: %__MODULE__{
    :Code => String.t,
    :Value => String.t,
    :Language => String.t,
    :Label => String.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.ExtendedStandardDataItem do
  def decode(value, _options) do
    value
  end
end
