# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.ExtractionItem do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Data,
    :Attachments
  ]

  @type t :: %__MODULE__{
    :Data => IndaHr.Model.ResumeCommonData.t,
    :Attachments => IndaHr.Model.ResumeAttachmentsV4.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.ExtractionItem do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Data, :struct, IndaHr.Model.ResumeCommonData, options)
    |> deserialize(:Attachments, :struct, IndaHr.Model.ResumeAttachmentsV4, options)
  end
end
