# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.FeedbackInfoItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ParseResumeOutput,
    :OutputCorrected
  ]

  @type t :: %__MODULE__{
    :ParseResumeOutput => inda_hr.Model.FeedbackExtractionItem.t,
    :OutputCorrected => inda_hr.Model.FeedbackBaseItem.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.FeedbackInfoItem do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ParseResumeOutput, :struct, inda_hr.Model.FeedbackExtractionItem, options)
    |> deserialize(:OutputCorrected, :struct, inda_hr.Model.FeedbackBaseItem, options)
  end
end

