# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.FeedbackData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :JobTitle,
    :PersonalInfo,
    :ContactInfo,
    :PersonLocation,
    :Headline,
    :EducationExperiences,
    :WorkExperiences,
    :CoverLetter,
    :References,
    :ProfileSummary,
    :Skills,
    :JobTitles,
    :Languages,
    :Certifications,
    :Publications,
    :Awards,
    :Projects,
    :Achievements,
    :Patents,
    :HobbiesAndInterests,
    :Licenses,
    :Volunteering,
    :ConferenceAndSeminars,
    :MilitaryHistory,
    :Others,
    :EducationExperience,
    :WorkExperience
  ]

  @type t :: %__MODULE__{
    :JobTitle => IndaHr.Model.OptionalResumeJobTitle.t | nil,
    :PersonalInfo => IndaHr.Model.PersonalInfo.t | nil,
    :ContactInfo => IndaHr.Model.ResumeContactInfoContactInfo.t | nil,
    :PersonLocation => IndaHr.Model.PersonLocation.t | nil,
    :Headline => IndaHr.Model.Text.t | nil,
    :EducationExperiences => [IndaHr.Model.EducationExperience.t] | nil,
    :WorkExperiences => [IndaHr.Model.WorkExperience.t] | nil,
    :CoverLetter => IndaHr.Model.Text.t | nil,
    :References => [IndaHr.Model.Reference.t] | nil,
    :ProfileSummary => IndaHr.Model.ProfileSummary.t | nil,
    :Skills => [IndaHr.Model.OptionalResumeSkill.t] | nil,
    :JobTitles => [IndaHr.Model.OptionalResumeJobTitle.t] | nil,
    :Languages => [IndaHr.Model.FeedbackLanguage.t] | nil,
    :Certifications => [IndaHr.Model.Certification.t] | nil,
    :Publications => [IndaHr.Model.Publication.t] | nil,
    :Awards => [IndaHr.Model.Award.t] | nil,
    :Projects => [IndaHr.Model.Project.t] | nil,
    :Achievements => [IndaHr.Model.Achievement.t] | nil,
    :Patents => [IndaHr.Model.Patent.t] | nil,
    :HobbiesAndInterests => [IndaHr.Model.Text.t] | nil,
    :Licenses => [IndaHr.Model.License.t] | nil,
    :Volunteering => [IndaHr.Model.Event.t] | nil,
    :ConferenceAndSeminars => [IndaHr.Model.Event.t] | nil,
    :MilitaryHistory => [IndaHr.Model.MilitaryService.t] | nil,
    :Others => [IndaHr.Model.Other.t] | nil,
    :EducationExperience => [IndaHr.Model.FeedbackEducationExperience.t] | nil,
    :WorkExperience => [IndaHr.Model.FeedbackWorkExperience.t] | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.FeedbackData do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:JobTitle, :struct, IndaHr.Model.OptionalResumeJobTitle, options)
    |> deserialize(:PersonalInfo, :struct, IndaHr.Model.PersonalInfo, options)
    |> deserialize(:ContactInfo, :struct, IndaHr.Model.ResumeContactInfoContactInfo, options)
    |> deserialize(:PersonLocation, :struct, IndaHr.Model.PersonLocation, options)
    |> deserialize(:Headline, :struct, IndaHr.Model.Text, options)
    |> deserialize(:EducationExperiences, :list, IndaHr.Model.EducationExperience, options)
    |> deserialize(:WorkExperiences, :list, IndaHr.Model.WorkExperience, options)
    |> deserialize(:CoverLetter, :struct, IndaHr.Model.Text, options)
    |> deserialize(:References, :list, IndaHr.Model.Reference, options)
    |> deserialize(:ProfileSummary, :struct, IndaHr.Model.ProfileSummary, options)
    |> deserialize(:Skills, :list, IndaHr.Model.OptionalResumeSkill, options)
    |> deserialize(:JobTitles, :list, IndaHr.Model.OptionalResumeJobTitle, options)
    |> deserialize(:Languages, :list, IndaHr.Model.FeedbackLanguage, options)
    |> deserialize(:Certifications, :list, IndaHr.Model.Certification, options)
    |> deserialize(:Publications, :list, IndaHr.Model.Publication, options)
    |> deserialize(:Awards, :list, IndaHr.Model.Award, options)
    |> deserialize(:Projects, :list, IndaHr.Model.Project, options)
    |> deserialize(:Achievements, :list, IndaHr.Model.Achievement, options)
    |> deserialize(:Patents, :list, IndaHr.Model.Patent, options)
    |> deserialize(:HobbiesAndInterests, :list, IndaHr.Model.Text, options)
    |> deserialize(:Licenses, :list, IndaHr.Model.License, options)
    |> deserialize(:Volunteering, :list, IndaHr.Model.Event, options)
    |> deserialize(:ConferenceAndSeminars, :list, IndaHr.Model.Event, options)
    |> deserialize(:MilitaryHistory, :list, IndaHr.Model.MilitaryService, options)
    |> deserialize(:Others, :list, IndaHr.Model.Other, options)
    |> deserialize(:EducationExperience, :list, IndaHr.Model.FeedbackEducationExperience, options)
    |> deserialize(:WorkExperience, :list, IndaHr.Model.FeedbackWorkExperience, options)
  end
end
