# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.FeedbackEntityInput do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :InputLanguage,
    :OutputLanguage,
    :EntityType,
    :AllowedOutputs,
    :ID
  ]

  @type t :: %__MODULE__{
    :InputLanguage => String.t | nil,
    :OutputLanguage => String.t | nil,
    :EntityType => String.t,
    :AllowedOutputs => [IndaHr.Model.AllowedOutput.t],
    :ID => IndaHr.Model.Id.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.FeedbackEntityInput do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:AllowedOutputs, :list, IndaHr.Model.AllowedOutput, options)
    |> deserialize(:ID, :struct, IndaHr.Model.Id, options)
  end
end
