# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.FeedbackBaseItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Data,
    :Attachments
  ]

  @type t :: %__MODULE__{
    :Data => inda_hr.Model.FeedbackData.t | nil,
    :Attachments => inda_hr.Model.FeedbackAttachments.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.FeedbackBaseItem do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Data, :struct, inda_hr.Model.FeedbackData, options)
    |> deserialize(:Attachments, :struct, inda_hr.Model.FeedbackAttachments, options)
  end
end

