# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.FinalGradeValue do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ScoreText",
    :"ScoreNumeric"
  ]

  @type t :: %__MODULE__{
    :"ScoreText" => String.t | nil,
    :"ScoreNumeric" => integer() | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.FinalGradeValue do
  def decode(value, _options) do
    value
  end
end

