# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.GeoLocation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Lat,
    :Lon
  ]

  @type t :: %__MODULE__{
    :Lat => float(),
    :Lon => float()
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.GeoLocation do
  def decode(value, _options) do
    value
  end
end

