# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.GetApplicationResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Data,
    :HiringDetails,
    :ResumeID,
    :JobAdID,
    :Metadata
  ]

  @type t :: %__MODULE__{
    :Data => IndaHr.Model.ApplicationCommonData.t | nil,
    :HiringDetails => IndaHr.Model.HiringDetails.t | nil,
    :ResumeID => String.t,
    :JobAdID => IndaHr.Model.Jobadid.t,
    :Metadata => IndaHr.Model.PublicMetadataModel.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.GetApplicationResponse do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Data, :struct, IndaHr.Model.ApplicationCommonData, options)
    |> deserialize(:HiringDetails, :struct, IndaHr.Model.HiringDetails, options)
    |> deserialize(:JobAdID, :struct, IndaHr.Model.Jobadid, options)
    |> deserialize(:Metadata, :struct, IndaHr.Model.PublicMetadataModel, options)
  end
end
