# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.GetCandidatesResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Total,
    :Hits,
    :SearchID,
    :JobAdID,
    :Resumes
  ]

  @type t :: %__MODULE__{
    :Total => integer() | nil,
    :Hits => integer() | nil,
    :SearchID => String.t | nil,
    :JobAdID => inda_hr.Model.Jobadid.t,
    :Resumes => [String.t]
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.GetCandidatesResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:JobAdID, :struct, inda_hr.Model.Jobadid, options)
  end
end

