# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.GetUniversityResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Data",
    :"ID",
    :"Metadata"
  ]

  @type t :: %__MODULE__{
    :"Data" => inda_hr.Model.UniversityData.t,
    :"ID" => String.t,
    :"Metadata" => inda_hr.Model.UniversityPublicMetadata.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.GetUniversityResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Data", :struct, inda_hr.Model.UniversityData, options)
    |> deserialize(:"Metadata", :struct, inda_hr.Model.UniversityPublicMetadata, options)
  end
end

