# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.GetUniversityResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Data,
    :ID,
    :Metadata
  ]

  @type t :: %__MODULE__{
    :Data => IndaHr.Model.UniversityData.t,
    :ID => String.t,
    :Metadata => IndaHr.Model.UniversityPublicMetadata.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.GetUniversityResponse do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Data, :struct, IndaHr.Model.UniversityData, options)
    |> deserialize(:Metadata, :struct, IndaHr.Model.UniversityPublicMetadata, options)
  end
end
