# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.GetStandardDataResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Data
  ]

  @type t :: %__MODULE__{
    :Data => [inda_hr.Model.StandardDataItem.t]
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.GetStandardDataResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Data, :list, inda_hr.Model.StandardDataItem, options)
  end
end

