# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.GetItemResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Data,
    :Metadata,
    :Attachments,
    :ID
  ]

  @type t :: %__MODULE__{
    :Data => IndaHr.Model.ResumeCommonData.t | nil,
    :Metadata => IndaHr.Model.ResumeCommonPublicMetadata.t,
    :Attachments => IndaHr.Model.PublicAttachments.t,
    :ID => String.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.GetItemResponse do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Data, :struct, IndaHr.Model.ResumeCommonData, options)
    |> deserialize(:Metadata, :struct, IndaHr.Model.ResumeCommonPublicMetadata, options)
    |> deserialize(:Attachments, :struct, IndaHr.Model.PublicAttachments, options)
  end
end
