# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.GroupByAdvancedApiCalls do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Advanced",
    :"NotAdvanced"
  ]

  @type t :: %__MODULE__{
    :"Advanced" => %{optional(String.t) => inda_hr.Model.SlimBaseResponse.t} | nil,
    :"NotAdvanced" => %{optional(String.t) => inda_hr.Model.SlimBaseResponse.t} | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.GroupByAdvancedApiCalls do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Advanced", :map, inda_hr.Model.SlimBaseResponse, options)
    |> deserialize(:"NotAdvanced", :map, inda_hr.Model.SlimBaseResponse, options)
  end
end

