# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.HiringDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ApplicationDate,
    :HiringDate,
    :HiringPipeline
  ]

  @type t :: %__MODULE__{
    :ApplicationDate => Date.t,
    :HiringDate => Date.t | nil,
    :HiringPipeline => [inda_hr.Model.HiringPipelineStage.t] | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.HiringDetails do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ApplicationDate, :date, nil, options)
    |> deserialize(:HiringDate, :date, nil, options)
    |> deserialize(:HiringPipeline, :list, inda_hr.Model.HiringPipelineStage, options)
  end
end

