# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.HistoryDetail do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Indexname,
    :Datetime,
    :StatusCode,
    :Advanced,
    :Price,
    :APICall
  ]

  @type t :: %__MODULE__{
    :Indexname => String.t,
    :Datetime => String.t,
    :StatusCode => integer(),
    :Advanced => boolean(),
    :Price => float(),
    :APICall => String.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.HistoryDetail do
  def decode(value, _options) do
    value
  end
end

