# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.History do
  @moduledoc """
  This object contains the history data according to the requested filters. If *Detail* has been set *true* in the request, an array of objects is returned. Each object is composed by the following fields, unless some aggregations have been requested: *APICall* (string), *Datetime* (string), *StatusCode* (int) and *Advanced* (boolean). If aggregation is performed, data is organized in nested objects (see the example below, where a *GroupBy* with *[\"advanced\", \"api_calls\"]* has been performed). Note that the *property name&ast;* shown in the response examples represents the API call name used to aggregate data if *api_calls* is set in the *GroupBy* field.
  """

  @derive [Poison.Encoder]
  defstruct [
    :Count,
    :Prices,
    :Detail,
    :Advanced,
    :NotAdvanced
  ]

  @type t :: %__MODULE__{
    :Count => integer(),
    :Prices => %{optional(String.t) => float()} | nil,
    :Detail => [IndaHr.Model.HistoryDetail.t] | nil,
    :Advanced => %{optional(String.t) => IndaHr.Model.SlimBaseResponse.t} | nil,
    :NotAdvanced => %{optional(String.t) => IndaHr.Model.SlimBaseResponse.t} | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.History do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Detail, :list, IndaHr.Model.HistoryDetail, options)
    |> deserialize(:Advanced, :map, IndaHr.Model.SlimBaseResponse, options)
    |> deserialize(:NotAdvanced, :map, IndaHr.Model.SlimBaseResponse, options)
  end
end
