# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.HttpValidationError do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :detail
  ]

  @type t :: %__MODULE__{
    :detail => [inda_hr.Model.ValidationError.t] | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.HttpValidationError do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:detail, :list, inda_hr.Model.ValidationError, options)
  end
end

