# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.IdEntityInput do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :EntityID,
    :Entity
  ]

  @type t :: %__MODULE__{
    :EntityID => String.t,
    :Entity => IndaHr.Model.EntityInput.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.IdEntityInput do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Entity, :struct, IndaHr.Model.EntityInput, options)
  end
end
