# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.ImportResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ImportID",
    :"Stats",
    :"Resumes",
    :"Errors"
  ]

  @type t :: %__MODULE__{
    :"ImportID" => String.t,
    :"Stats" => inda_hr.Model.UploadStats.t,
    :"Resumes" => [inda_hr.Model.ImportItemResponse.t],
    :"Errors" => [inda_hr.Model.ImportErrorResponse.t] | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.ImportResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Stats", :struct, inda_hr.Model.UploadStats, options)
    |> deserialize(:"Resumes", :list, inda_hr.Model.ImportItemResponse, options)
    |> deserialize(:"Errors", :list, inda_hr.Model.ImportErrorResponse, options)
  end
end

