# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.ImportItemResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"InternalID",
    :"ResumeID"
  ]

  @type t :: %__MODULE__{
    :"InternalID" => inda_hr.Model.Internalid.t,
    :"ResumeID" => String.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.ImportItemResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"InternalID", :struct, inda_hr.Model.Internalid, options)
  end
end

