# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.IndexedDocumentFailuresResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :DocType,
    :Indexname,
    :Count,
    :ImportID,
    :Failures
  ]

  @type t :: %__MODULE__{
    :DocType => String.t | nil,
    :Indexname => String.t,
    :Count => integer(),
    :ImportID => String.t | nil,
    :Failures => [inda_hr.Model.IndexedDocumentFailure.t]
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.IndexedDocumentFailuresResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Failures, :list, inda_hr.Model.IndexedDocumentFailure, options)
  end
end

