# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.IndexCreditsInfo do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Indexname,
    :Suite,
    :History
  ]

  @type t :: %__MODULE__{
    :Indexname => String.t,
    :Suite => IndaHr.Model.SuiteResponse.t | nil,
    :History => IndaHr.Model.History.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.IndexCreditsInfo do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Suite, :struct, IndaHr.Model.SuiteResponse, options)
    |> deserialize(:History, :struct, IndaHr.Model.History, options)
  end
end
