# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.Industries do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Industry,
    :Frequency
  ]

  @type t :: %__MODULE__{
    :Industry => String.t | nil,
    :Frequency => float() | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.Industries do
  def decode(value, _options) do
    value
  end
end
