# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.JobAdRemoteWorking do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Type",
    :"Frequency"
  ]

  @type t :: %__MODULE__{
    :"Type" => inda_hr.Model.JobAdRemoteWorkingType.t | nil,
    :"Frequency" => AnyOfRemoteWorkingFrequencyValueRemoteWorkingFrequencyRange | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.JobAdRemoteWorking do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Type", :struct, inda_hr.Model.JobAdRemoteWorkingType, options)
    |> deserialize(:"Frequency", :struct, inda_hr.Model.AnyOfRemoteWorkingFrequencyValueRemoteWorkingFrequencyRange, options)
  end
end

