# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.JobAdFullTextSearch do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :QueryTerms,
    :QueryFilters
  ]

  @type t :: %__MODULE__{
    :QueryTerms => [IndaHr.Model.JobadRequestsSimpleTerm.t],
    :QueryFilters => IndaHr.Model.QueryFilters.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.JobAdFullTextSearch do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:QueryTerms, :list, IndaHr.Model.JobadRequestsSimpleTerm, options)
    |> deserialize(:QueryFilters, :struct, IndaHr.Model.QueryFilters, options)
  end
end
