# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.JobAdSearchQuery do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :QueryFilters
  ]

  @type t :: %__MODULE__{
    :QueryFilters => IndaHr.Model.BaseJobAdSearchQuery.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.JobAdSearchQuery do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:QueryFilters, :struct, IndaHr.Model.BaseJobAdSearchQuery, options)
  end
end
