# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.JobAdRemoteWorking do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Type,
    :Frequency
  ]

  @type t :: %__MODULE__{
    :Type => IndaHr.Model.JobAdRemoteWorkingType.t | nil,
    :Frequency => IndaHr.Model.Frequency1.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.JobAdRemoteWorking do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Type, :struct, IndaHr.Model.JobAdRemoteWorkingType, options)
    |> deserialize(:Frequency, :struct, IndaHr.Model.Frequency1, options)
  end
end
