# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.JobAdSkillsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Hits",
    :"Attachments",
    :"Skills"
  ]

  @type t :: %__MODULE__{
    :"Hits" => integer(),
    :"Attachments" => inda_hr.Model.AttachmentsV3.t | nil,
    :"Skills" => [inda_hr.Model.SlimJobAdSkill.t]
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.JobAdSkillsResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Attachments", :struct, inda_hr.Model.AttachmentsV3, options)
    |> deserialize(:"Skills", :list, inda_hr.Model.SlimJobAdSkill, options)
  end
end

