# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.JobAd do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Data,
    :Metadata
  ]

  @type t :: %__MODULE__{
    :Data => IndaHr.Model.JobAdMatchingData.t,
    :Metadata => IndaHr.Model.MatchingJobadMatchingPublicMetadata.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.JobAd do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Data, :struct, IndaHr.Model.JobAdMatchingData, options)
    |> deserialize(:Metadata, :struct, IndaHr.Model.MatchingJobadMatchingPublicMetadata, options)
  end
end
