# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.JobAdSkillsResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Hits,
    :Attachments,
    :Skills
  ]

  @type t :: %__MODULE__{
    :Hits => integer(),
    :Attachments => IndaHr.Model.AttachmentsV3.t | nil,
    :Skills => [IndaHr.Model.SlimJobAdSkill.t]
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.JobAdSkillsResponse do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Attachments, :struct, IndaHr.Model.AttachmentsV3, options)
    |> deserialize(:Skills, :list, IndaHr.Model.SlimJobAdSkill, options)
  end
end
