# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.JobAdJobTitlesResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Hits",
    :"JobTitles"
  ]

  @type t :: %__MODULE__{
    :"Hits" => integer(),
    :"JobTitles" => [inda_hr.Model.JobAdJobTitle.t] | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.JobAdJobTitlesResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"JobTitles", :list, inda_hr.Model.JobAdJobTitle, options)
  end
end

