# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.JobDescription do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :CompanyDescription,
    :PositionDescription,
    :PositionRequirements,
    :AdditionalInformation
  ]

  @type t :: %__MODULE__{
    :CompanyDescription => IndaHr.Model.Section.t | nil,
    :PositionDescription => IndaHr.Model.Section.t,
    :PositionRequirements => IndaHr.Model.Section.t | nil,
    :AdditionalInformation => IndaHr.Model.Section.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.JobDescription do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:CompanyDescription, :struct, IndaHr.Model.Section, options)
    |> deserialize(:PositionDescription, :struct, IndaHr.Model.Section, options)
    |> deserialize(:PositionRequirements, :struct, IndaHr.Model.Section, options)
    |> deserialize(:AdditionalInformation, :struct, IndaHr.Model.Section, options)
  end
end
