# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.JobAdJobTitlesResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Hits,
    :Attachments,
    :JobTitles
  ]

  @type t :: %__MODULE__{
    :Hits => integer(),
    :Attachments => inda_hr.Model.AttachmentsV3.t | nil,
    :JobTitles => [inda_hr.Model.SlimJobAdJobTitle.t]
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.JobAdJobTitlesResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Attachments, :struct, inda_hr.Model.AttachmentsV3, options)
    |> deserialize(:JobTitles, :list, inda_hr.Model.SlimJobAdJobTitle, options)
  end
end

