# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.JobadMatchingEvidenceQuery do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :JobAdIDs,
    :Resume
  ]

  @type t :: %__MODULE__{
    :JobAdIDs => [String.t],
    :Resume => IndaHr.Model.Resume.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.JobadMatchingEvidenceQuery do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Resume, :struct, IndaHr.Model.Resume, options)
  end
end
