# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.JobadMatchingQuery do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"QueryFilters",
    :"Resume"
  ]

  @type t :: %__MODULE__{
    :"QueryFilters" => inda_hr.Model.QueryFilters.t | nil,
    :"Resume" => inda_hr.Model.MatchingResumeDocument.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.JobadMatchingQuery do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"QueryFilters", :struct, inda_hr.Model.QueryFilters, options)
    |> deserialize(:"Resume", :struct, inda_hr.Model.MatchingResumeDocument, options)
  end
end

