# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.JobadCommonMinimalData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"JobTitle",
    :"EmployerID"
  ]

  @type t :: %__MODULE__{
    :"JobTitle" => inda_hr.Model.JobTitleHeader.t,
    :"EmployerID" => String.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.JobadCommonMinimalData do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"JobTitle", :struct, inda_hr.Model.JobTitleHeader, options)
  end
end

