# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.JobadPhoneNumbersNumber do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Value
  ]

  @type t :: %__MODULE__{
    :Value => IndaHr.Model.OptionalPhoneNumber.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.JobadPhoneNumbersNumber do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Value, :struct, IndaHr.Model.OptionalPhoneNumber, options)
  end
end
