# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.JobadMatchingEvidenceQuery do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"JobAdIDs",
    :"Resume"
  ]

  @type t :: %__MODULE__{
    :"JobAdIDs" => [String.t],
    :"Resume" => inda_hr.Model.Resume.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.JobadMatchingEvidenceQuery do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Resume", :struct, inda_hr.Model.Resume, options)
  end
end

