# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.JobadIdAnyOf do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [

  ]

  @type t :: %__MODULE__{

  }
end

defimpl Poison.Decoder, for: IndaHr.Model.JobadIdAnyOf do
  def decode(value, _options) do
    value
  end
end
