# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.JobadContactInfoContactInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :PersonName,
    :PhoneNumbers,
    :EmailAddresses,
    :Links
  ]

  @type t :: %__MODULE__{
    :PersonName => inda_hr.Model.JobadContactInfoPersonName.t | nil,
    :PhoneNumbers => [inda_hr.Model.JobadPhoneNumbersPhoneNumber.t] | nil,
    :EmailAddresses => [inda_hr.Model.JobadEmailAddressEmailAddress.t] | nil,
    :Links => [inda_hr.Model.JobadLinkLink.t] | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.JobadContactInfoContactInfo do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:PersonName, :struct, inda_hr.Model.JobadContactInfoPersonName, options)
    |> deserialize(:PhoneNumbers, :list, inda_hr.Model.JobadPhoneNumbersPhoneNumber, options)
    |> deserialize(:EmailAddresses, :list, inda_hr.Model.JobadEmailAddressEmailAddress, options)
    |> deserialize(:Links, :list, inda_hr.Model.JobadLinkLink, options)
  end
end

