# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.KeywordsOut do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Query,
    :Language,
    :Results
  ]

  @type t :: %__MODULE__{
    :Query => String.t,
    :Language => String.t,
    :Results => [IndaHr.Model.SearchTerm.t]
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.KeywordsOut do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Results, :list, IndaHr.Model.SearchTerm, options)
  end
end
