# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.KeywordsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Hits",
    :"Errors",
    :"Out"
  ]

  @type t :: %__MODULE__{
    :"Hits" => integer() | nil,
    :"Errors" => integer(),
    :"Out" => [inda_hr.Model.KeywordsOut.t]
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.KeywordsResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Out", :list, inda_hr.Model.KeywordsOut, options)
  end
end

