# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.MatchResumeEvidenceElement do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :Education,
    :Experience,
    :Skills,
    :JobTitles
  ]

  @type t :: %__MODULE__{
    :ID => String.t,
    :Education => IndaHr.Model.MatchResumeEvidenceEducation.t,
    :Experience => IndaHr.Model.MatchResumeEvidenceExperience.t,
    :Skills => [IndaHr.Model.MatchResumeEvidenceSkill.t],
    :JobTitles => [IndaHr.Model.MatchResumeEvidenceJobTitle.t]
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.MatchResumeEvidenceElement do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Education, :struct, IndaHr.Model.MatchResumeEvidenceEducation, options)
    |> deserialize(:Experience, :struct, IndaHr.Model.MatchResumeEvidenceExperience, options)
    |> deserialize(:Skills, :list, IndaHr.Model.MatchResumeEvidenceSkill, options)
    |> deserialize(:JobTitles, :list, IndaHr.Model.MatchResumeEvidenceJobTitle, options)
  end
end
