# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.MatchEvidenceTerm do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Details",
    :"Weight",
    :"Score",
    :"Term"
  ]

  @type t :: %__MODULE__{
    :"Details" => inda_hr.Model.RelatedTerms.t | nil,
    :"Weight" => float() | nil,
    :"Score" => float(),
    :"Term" => String.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.MatchEvidenceTerm do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Details", :struct, inda_hr.Model.RelatedTerms, options)
  end
end

