# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.MatchResumeEvidenceJobTitle do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Score,
    :JobTitle
  ]

  @type t :: %__MODULE__{
    :Score => float(),
    :JobTitle => inda_hr.Model.ResumeJobTitle.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.MatchResumeEvidenceJobTitle do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:JobTitle, :struct, inda_hr.Model.ResumeJobTitle, options)
  end
end

