# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.MatchResumeEvidenceSkill do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Score,
    :Skill
  ]

  @type t :: %__MODULE__{
    :Score => float(),
    :Skill => inda_hr.Model.ResumeSkill.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.MatchResumeEvidenceSkill do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Skill, :struct, inda_hr.Model.ResumeSkill, options)
  end
end

