# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.MatchResumeEvidenceExperience do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Duration,
    :Seniority
  ]

  @type t :: %__MODULE__{
    :Duration => IndaHr.Model.MatchResumeEvidenceDuration.t,
    :Seniority => IndaHr.Model.MatchResumeEvidenceSeniority.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.MatchResumeEvidenceExperience do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Duration, :struct, IndaHr.Model.MatchResumeEvidenceDuration, options)
    |> deserialize(:Seniority, :struct, IndaHr.Model.MatchResumeEvidenceSeniority, options)
  end
end
