# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.MatchJobAdEvidenceElement do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :Education,
    :Experience,
    :Skills,
    :JobTitles
  ]

  @type t :: %__MODULE__{
    :ID => String.t,
    :Education => IndaHr.Model.RequiredAndPreferredMatchJobAdEvidenceEducation.t,
    :Experience => IndaHr.Model.MatchJobAdEvidenceExperience.t,
    :Skills => IndaHr.Model.RequiredAndPreferredListMatchJobAdEvidenceSkill.t,
    :JobTitles => [IndaHr.Model.MatchJobAdEvidenceJobTitle.t]
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.MatchJobAdEvidenceElement do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Education, :struct, IndaHr.Model.RequiredAndPreferredMatchJobAdEvidenceEducation, options)
    |> deserialize(:Experience, :struct, IndaHr.Model.MatchJobAdEvidenceExperience, options)
    |> deserialize(:Skills, :struct, IndaHr.Model.RequiredAndPreferredListMatchJobAdEvidenceSkill, options)
    |> deserialize(:JobTitles, :list, IndaHr.Model.MatchJobAdEvidenceJobTitle, options)
  end
end
