# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.MatchJobAdEvidenceEducation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Title,
    :EducationLevelCode,
    :Score
  ]

  @type t :: %__MODULE__{
    :Title => inda_hr.Model.EducationTitleV7.t | nil,
    :EducationLevelCode => inda_hr.Model.JobadEducationEducationLevelCode.t | nil,
    :Score => float()
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.MatchJobAdEvidenceEducation do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Title, :struct, inda_hr.Model.EducationTitleV7, options)
    |> deserialize(:EducationLevelCode, :struct, inda_hr.Model.JobadEducationEducationLevelCode, options)
  end
end

