# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.MatchingDocumentAttachment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"CV"
  ]

  @type t :: %__MODULE__{
    :"CV" => inda_hr.Model.ResumeAttachmentDocument.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.MatchingDocumentAttachment do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"CV", :struct, inda_hr.Model.ResumeAttachmentDocument, options)
  end
end

