# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.MilitaryService do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"MilitaryBranch",
    :"MilitaryDivision",
    :"StartingRank",
    :"CurrentOrEndingRank",
    :"Location",
    :"StartDate",
    :"EndDate",
    :"Ongoing"
  ]

  @type t :: %__MODULE__{
    :"MilitaryBranch" => inda_hr.Model.Title.t | nil,
    :"MilitaryDivision" => inda_hr.Model.Title.t | nil,
    :"StartingRank" => inda_hr.Model.Title.t | nil,
    :"CurrentOrEndingRank" => inda_hr.Model.Title.t | nil,
    :"Location" => inda_hr.Model.ResumeLocationsLocation.t | nil,
    :"StartDate" => inda_hr.Model.DateTime.t | nil,
    :"EndDate" => inda_hr.Model.DateTime.t | nil,
    :"Ongoing" => inda_hr.Model.Ongoing.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.MilitaryService do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"MilitaryBranch", :struct, inda_hr.Model.Title, options)
    |> deserialize(:"MilitaryDivision", :struct, inda_hr.Model.Title, options)
    |> deserialize(:"StartingRank", :struct, inda_hr.Model.Title, options)
    |> deserialize(:"CurrentOrEndingRank", :struct, inda_hr.Model.Title, options)
    |> deserialize(:"Location", :struct, inda_hr.Model.ResumeLocationsLocation, options)
    |> deserialize(:"Ongoing", :struct, inda_hr.Model.Ongoing, options)
  end
end

