# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.MongoDbGeoLocation do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Lat,
    :Lon
  ]

  @type t :: %__MODULE__{
    :Lat => float(),
    :Lon => float()
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.MongoDbGeoLocation do
  def decode(value, _options) do
    value
  end
end
