# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.MostSimilarSkillResponseCategorized do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Skill
  ]

  @type t :: %__MODULE__{
    :Skill => inda_hr.Model.EscoCommonSkill.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.MostSimilarSkillResponseCategorized do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Skill, :struct, inda_hr.Model.EscoCommonSkill, options)
  end
end

