# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.MostRecentResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :DocType,
    :Indexname,
    :Hits,
    :Total,
    :Out
  ]

  @type t :: %__MODULE__{
    :DocType => String.t | nil,
    :Indexname => String.t,
    :Hits => integer(),
    :Total => integer(),
    :Out => [IndaHr.Model.MostRecentItem.t]
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.MostRecentResponse do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Out, :list, IndaHr.Model.MostRecentItem, options)
  end
end
