# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.MostSimilarSkillResponseCategorized do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Skill"
  ]

  @type t :: %__MODULE__{
    :"Skill" => inda_hr.Model.EscoCommonSkill.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.MostSimilarSkillResponseCategorized do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Skill", :struct, inda_hr.Model.EscoCommonSkill, options)
  end
end

