# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.MostRecentItem do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Data",
    :"Metadata",
    :"Attachments",
    :"ID"
  ]

  @type t :: %__MODULE__{
    :"Data" => inda_hr.Model.ResumeCommonMinimalData.t | nil,
    :"Metadata" => inda_hr.Model.ResumeCommonPublicMetadata.t,
    :"Attachments" => inda_hr.Model.MinimalPublicAttachments.t,
    :"ID" => String.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.MostRecentItem do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Data", :struct, inda_hr.Model.ResumeCommonMinimalData, options)
    |> deserialize(:"Metadata", :struct, inda_hr.Model.ResumeCommonPublicMetadata, options)
    |> deserialize(:"Attachments", :struct, inda_hr.Model.MinimalPublicAttachments, options)
  end
end

