# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.MultiEntityInput do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Entities
  ]

  @type t :: %__MODULE__{
    :Entities => [inda_hr.Model.IdEntityInput.t]
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.MultiEntityInput do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Entities, :list, inda_hr.Model.IdEntityInput, options)
  end
end

