# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.MultiEntityInput do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Entities
  ]

  @type t :: %__MODULE__{
    :Entities => [IndaHr.Model.IdEntityInput.t]
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.MultiEntityInput do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Entities, :list, IndaHr.Model.IdEntityInput, options)
  end
end
