# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.OptionalEscoOccupationMatch do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Score,
    :ConceptType,
    :PreferredLabel,
    :AltLabels,
    :Description,
    :Language,
    :MatchDetails,
    :ISCOGroup,
    :Code,
    :Skills
  ]

  @type t :: %__MODULE__{
    :Score => float() | nil,
    :ConceptType => String.t | nil,
    :PreferredLabel => String.t | nil,
    :AltLabels => String.t | nil,
    :Description => String.t | nil,
    :Language => String.t | nil,
    :MatchDetails => IndaHr.Model.OptionalEscoMatchDetails.t | nil,
    :ISCOGroup => String.t | nil,
    :Code => String.t | nil,
    :Skills => [IndaHr.Model.OptionalEscoSkill.t] | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.OptionalEscoOccupationMatch do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:MatchDetails, :struct, IndaHr.Model.OptionalEscoMatchDetails, options)
    |> deserialize(:Skills, :list, IndaHr.Model.OptionalEscoSkill, options)
  end
end
