# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.OptionalLibraryDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :URL,
    :AdditionalInfo
  ]

  @type t :: %__MODULE__{
    :URL => String.t | nil,
    :AdditionalInfo => String.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.OptionalLibraryDetails do
  def decode(value, _options) do
    value
  end
end

