# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.OptionalCarnegieClassification do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :BasicClassification,
    :"2000Classification",
    :"Size&Setting",
    :EnrollmentProfile,
    :UndergraduateProfile,
    :UndergraduateInstructionalProgram,
    :GraduateInstructionalProgram
  ]

  @type t :: %__MODULE__{
    :BasicClassification => IndaHr.Model.UniversityAdmissionsValueModelStr.t | nil,
    :"2000Classification" => IndaHr.Model.UniversityAdmissionsValueModelStr.t | nil,
    :"Size&Setting" => IndaHr.Model.UniversityAdmissionsValueModelStr.t | nil,
    :EnrollmentProfile => IndaHr.Model.UniversityAdmissionsValueModelStr.t | nil,
    :UndergraduateProfile => IndaHr.Model.UniversityAdmissionsValueModelStr.t | nil,
    :UndergraduateInstructionalProgram => IndaHr.Model.UniversityAdmissionsValueModelStr.t | nil,
    :GraduateInstructionalProgram => IndaHr.Model.UniversityAdmissionsValueModelStr.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.OptionalCarnegieClassification do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:BasicClassification, :struct, IndaHr.Model.UniversityAdmissionsValueModelStr, options)
    |> deserialize(:"2000Classification", :struct, IndaHr.Model.UniversityAdmissionsValueModelStr, options)
    |> deserialize(:"Size&Setting", :struct, IndaHr.Model.UniversityAdmissionsValueModelStr, options)
    |> deserialize(:EnrollmentProfile, :struct, IndaHr.Model.UniversityAdmissionsValueModelStr, options)
    |> deserialize(:UndergraduateProfile, :struct, IndaHr.Model.UniversityAdmissionsValueModelStr, options)
    |> deserialize(:UndergraduateInstructionalProgram, :struct, IndaHr.Model.UniversityAdmissionsValueModelStr, options)
    |> deserialize(:GraduateInstructionalProgram, :struct, IndaHr.Model.UniversityAdmissionsValueModelStr, options)
  end
end
