# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.OptionalAccreditationsDetails do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :URL,
    :YearOfFirstAccreditation,
    :OtherAccreditations
  ]

  @type t :: %__MODULE__{
    :URL => String.t | nil,
    :YearOfFirstAccreditation => IndaHr.Model.Yearoffirstaccreditation.t | nil,
    :OtherAccreditations => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.OptionalAccreditationsDetails do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:YearOfFirstAccreditation, :struct, IndaHr.Model.Yearoffirstaccreditation, options)
  end
end
