# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.OptionalEscoSkill do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ConceptType",
    :"PreferredLabel",
    :"AltLabels",
    :"Description",
    :"SkillType",
    :"ReuseLevel"
  ]

  @type t :: %__MODULE__{
    :"ConceptType" => String.t | nil,
    :"PreferredLabel" => String.t | nil,
    :"AltLabels" => String.t | nil,
    :"Description" => String.t | nil,
    :"SkillType" => String.t | nil,
    :"ReuseLevel" => String.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.OptionalEscoSkill do
  def decode(value, _options) do
    value
  end
end

