# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.OptionalAccreditationsDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :URL,
    :YearOfFirstAccreditation,
    :OtherAccreditations
  ]

  @type t :: %__MODULE__{
    :URL => String.t | nil,
    :YearOfFirstAccreditation => inda_hr.Model.Yearoffirstaccreditation.t | nil,
    :OtherAccreditations => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.OptionalAccreditationsDetails do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:YearOfFirstAccreditation, :struct, inda_hr.Model.Yearoffirstaccreditation, options)
  end
end

