# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.OptionalFacilitiesAndServices do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Library",
    :"Housing",
    :"SportFacilities",
    :"FinancialAids",
    :"StudyAbroad",
    :"DistanceLearning",
    :"AcademicCounseling",
    :"CareerServices",
    :"InstitutionalHospital"
  ]

  @type t :: %__MODULE__{
    :"Library" => inda_hr.Model.OptionalLibrary.t | nil,
    :"Housing" => inda_hr.Model.OptionalHousing.t | nil,
    :"SportFacilities" => inda_hr.Model.OptionalSportFacilities.t | nil,
    :"FinancialAids" => inda_hr.Model.OptionalFinancialAids.t | nil,
    :"StudyAbroad" => inda_hr.Model.OptionalStudyAbroad.t | nil,
    :"DistanceLearning" => inda_hr.Model.OptionalDistanceLearning.t | nil,
    :"AcademicCounseling" => inda_hr.Model.OptionalAcademicCounseling.t | nil,
    :"CareerServices" => inda_hr.Model.OptionalCareerServices.t | nil,
    :"InstitutionalHospital" => inda_hr.Model.OptionalInstitutionalHospital.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.OptionalFacilitiesAndServices do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Library", :struct, inda_hr.Model.OptionalLibrary, options)
    |> deserialize(:"Housing", :struct, inda_hr.Model.OptionalHousing, options)
    |> deserialize(:"SportFacilities", :struct, inda_hr.Model.OptionalSportFacilities, options)
    |> deserialize(:"FinancialAids", :struct, inda_hr.Model.OptionalFinancialAids, options)
    |> deserialize(:"StudyAbroad", :struct, inda_hr.Model.OptionalStudyAbroad, options)
    |> deserialize(:"DistanceLearning", :struct, inda_hr.Model.OptionalDistanceLearning, options)
    |> deserialize(:"AcademicCounseling", :struct, inda_hr.Model.OptionalAcademicCounseling, options)
    |> deserialize(:"CareerServices", :struct, inda_hr.Model.OptionalCareerServices, options)
    |> deserialize(:"InstitutionalHospital", :struct, inda_hr.Model.OptionalInstitutionalHospital, options)
  end
end

