# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.OptionalEscoSkillMatch do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Score,
    :ConceptType,
    :PreferredLabel,
    :AltLabels,
    :Description,
    :Language,
    :MatchDetails,
    :SkillType,
    :ReuseLevel,
    :ConceptUri,
    :Occupations
  ]

  @type t :: %__MODULE__{
    :Score => float() | nil,
    :ConceptType => String.t | nil,
    :PreferredLabel => String.t | nil,
    :AltLabels => String.t | nil,
    :Description => String.t | nil,
    :Language => String.t | nil,
    :MatchDetails => IndaHr.Model.OptionalEscoMatchDetails.t | nil,
    :SkillType => String.t | nil,
    :ReuseLevel => String.t | nil,
    :ConceptUri => String.t | nil,
    :Occupations => [IndaHr.Model.OptionalEscoOccupationSkill.t] | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.OptionalEscoSkillMatch do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:MatchDetails, :struct, IndaHr.Model.OptionalEscoMatchDetails, options)
    |> deserialize(:Occupations, :list, IndaHr.Model.OptionalEscoOccupationSkill, options)
  end
end
