# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.OptionalEscoJobtitleMatchCategorized do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Code,
    :PreferredLabel,
    :Description,
    :Language,
    :Score,
    :OccupationHierarchy,
    :Industries,
    :JobFunctions
  ]

  @type t :: %__MODULE__{
    :Code => String.t | nil,
    :PreferredLabel => String.t | nil,
    :Description => String.t | nil,
    :Language => String.t | nil,
    :Score => float() | nil,
    :OccupationHierarchy => IndaHr.Model.OccupationHierarchy.t | nil,
    :Industries => [IndaHr.Model.Industries.t] | nil,
    :JobFunctions => [IndaHr.Model.Jobfunctions.t] | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.OptionalEscoJobtitleMatchCategorized do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:OccupationHierarchy, :struct, IndaHr.Model.OccupationHierarchy, options)
    |> deserialize(:Industries, :list, IndaHr.Model.Industries, options)
    |> deserialize(:JobFunctions, :list, IndaHr.Model.Jobfunctions, options)
  end
end
