# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.OptionalPublisher do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Name",
    :"Category",
    :"Link"
  ]

  @type t :: %__MODULE__{
    :"Name" => inda_hr.Model.JobadSectionsValueModelStrictStr.t | nil,
    :"Category" => inda_hr.Model.JobadSectionsValueModelStrictStr.t | nil,
    :"Link" => inda_hr.Model.OptionalLink.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.OptionalPublisher do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Name", :struct, inda_hr.Model.JobadSectionsValueModelStrictStr, options)
    |> deserialize(:"Category", :struct, inda_hr.Model.JobadSectionsValueModelStrictStr, options)
    |> deserialize(:"Link", :struct, inda_hr.Model.OptionalLink, options)
  end
end

