# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.OptionalMetadata do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Language
  ]

  @type t :: %__MODULE__{
    :Language => String.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.OptionalMetadata do
  def decode(value, _options) do
    value
  end
end
