# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.OptionalEntityBaseDetails do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :IsValidated,
    :EntityType
  ]

  @type t :: %__MODULE__{
    :IsValidated => boolean() | nil,
    :EntityType => String.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.OptionalEntityBaseDetails do
  def decode(value, _options) do
    value
  end
end
