# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.OptionalCarnegieClassification do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"BasicClassification",
    :"2000Classification",
    :"Size&Setting",
    :"EnrollmentProfile",
    :"UndergraduateProfile",
    :"UndergraduateInstructionalProgram",
    :"GraduateInstructionalProgram"
  ]

  @type t :: %__MODULE__{
    :"BasicClassification" => inda_hr.Model.ValueModelStr.t | nil,
    :"2000Classification" => inda_hr.Model.ValueModelStr.t | nil,
    :"Size&Setting" => inda_hr.Model.ValueModelStr.t | nil,
    :"EnrollmentProfile" => inda_hr.Model.ValueModelStr.t | nil,
    :"UndergraduateProfile" => inda_hr.Model.ValueModelStr.t | nil,
    :"UndergraduateInstructionalProgram" => inda_hr.Model.ValueModelStr.t | nil,
    :"GraduateInstructionalProgram" => inda_hr.Model.ValueModelStr.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.OptionalCarnegieClassification do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"BasicClassification", :struct, inda_hr.Model.ValueModelStr, options)
    |> deserialize(:"2000Classification", :struct, inda_hr.Model.ValueModelStr, options)
    |> deserialize(:"Size&Setting", :struct, inda_hr.Model.ValueModelStr, options)
    |> deserialize(:"EnrollmentProfile", :struct, inda_hr.Model.ValueModelStr, options)
    |> deserialize(:"UndergraduateProfile", :struct, inda_hr.Model.ValueModelStr, options)
    |> deserialize(:"UndergraduateInstructionalProgram", :struct, inda_hr.Model.ValueModelStr, options)
    |> deserialize(:"GraduateInstructionalProgram", :struct, inda_hr.Model.ValueModelStr, options)
  end
end

