# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.OptionalRequiredAndPreferredSeniorityValue do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Required,
    :Preferred
  ]

  @type t :: %__MODULE__{
    :Required => IndaHr.Model.SeniorityValue.t | nil,
    :Preferred => IndaHr.Model.SeniorityValue.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.OptionalRequiredAndPreferredSeniorityValue do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Required, :struct, IndaHr.Model.SeniorityValue, options)
    |> deserialize(:Preferred, :struct, IndaHr.Model.SeniorityValue, options)
  end
end
