# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.Organization do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :OrganizationName,
    :Department,
    :Location,
    :Link,
    :ID
  ]

  @type t :: %__MODULE__{
    :OrganizationName => inda_hr.Model.BaseModelsName.t | nil,
    :Department => inda_hr.Model.Text.t | nil,
    :Location => inda_hr.Model.ResumeLocationsLocation.t | nil,
    :Link => inda_hr.Model.ResumeLinkLink.t | nil,
    :ID => inda_hr.Model.Id.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.Organization do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:OrganizationName, :struct, inda_hr.Model.BaseModelsName, options)
    |> deserialize(:Department, :struct, inda_hr.Model.Text, options)
    |> deserialize(:Location, :struct, inda_hr.Model.ResumeLocationsLocation, options)
    |> deserialize(:Link, :struct, inda_hr.Model.ResumeLinkLink, options)
    |> deserialize(:ID, :struct, inda_hr.Model.Id, options)
  end
end

