# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.PatchApplicationRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Data
  ]

  @type t :: %__MODULE__{
    :Data => IndaHr.Model.ApplicationCommonOptionalData.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.PatchApplicationRequest do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Data, :struct, IndaHr.Model.ApplicationCommonOptionalData, options)
  end
end
