# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.Patent do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :PatentTitle,
    :PatentID,
    :PatentStatus,
    :Description,
    :InventorNames,
    :IssuingAuthority
  ]

  @type t :: %__MODULE__{
    :PatentTitle => IndaHr.Model.Title.t | nil,
    :PatentID => IndaHr.Model.Text.t | nil,
    :PatentStatus => IndaHr.Model.PatentStatus.t | nil,
    :Description => IndaHr.Model.Description.t | nil,
    :InventorNames => [IndaHr.Model.ResumePersonNamePersonName.t] | nil,
    :IssuingAuthority => IndaHr.Model.Organization.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.Patent do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:PatentTitle, :struct, IndaHr.Model.Title, options)
    |> deserialize(:PatentID, :struct, IndaHr.Model.Text, options)
    |> deserialize(:PatentStatus, :struct, IndaHr.Model.PatentStatus, options)
    |> deserialize(:Description, :struct, IndaHr.Model.Description, options)
    |> deserialize(:InventorNames, :list, IndaHr.Model.ResumePersonNamePersonName, options)
    |> deserialize(:IssuingAuthority, :struct, IndaHr.Model.Organization, options)
  end
end
