# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.PicAttachmentImage do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Pic
  ]

  @type t :: %__MODULE__{
    :Pic => IndaHr.Model.Image.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.PicAttachmentImage do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Pic, :struct, IndaHr.Model.Image, options)
  end
end
