# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.Project do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ProjectName,
    :Description,
    :Roles,
    :Keywords,
    :StartDate,
    :EndDate,
    :Ongoing,
    :Link
  ]

  @type t :: %__MODULE__{
    :ProjectName => IndaHr.Model.BaseModelsName.t | nil,
    :Description => IndaHr.Model.Description.t | nil,
    :Roles => [IndaHr.Model.Role.t] | nil,
    :Keywords => [IndaHr.Model.Keyword.t] | nil,
    :StartDate => IndaHr.Model.DateTime.t | nil,
    :EndDate => IndaHr.Model.DateTime.t | nil,
    :Ongoing => IndaHr.Model.Ongoing.t | nil,
    :Link => IndaHr.Model.ResumeLinkLink.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.Project do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ProjectName, :struct, IndaHr.Model.BaseModelsName, options)
    |> deserialize(:Description, :struct, IndaHr.Model.Description, options)
    |> deserialize(:Roles, :list, IndaHr.Model.Role, options)
    |> deserialize(:Keywords, :list, IndaHr.Model.Keyword, options)
    |> deserialize(:Ongoing, :struct, IndaHr.Model.Ongoing, options)
    |> deserialize(:Link, :struct, IndaHr.Model.ResumeLinkLink, options)
  end
end
