# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.PublicMetadataModel do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"CreationDate",
    :"LastModified"
  ]

  @type t :: %__MODULE__{
    :"CreationDate" => DateTime.t,
    :"LastModified" => DateTime.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.PublicMetadataModel do
  def decode(value, _options) do
    value
  end
end

