# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.Publication do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Title,
    :Description,
    :DOI,
    :Year,
    :Link
  ]

  @type t :: %__MODULE__{
    :Title => IndaHr.Model.Title.t | nil,
    :Description => IndaHr.Model.Description.t | nil,
    :DOI => IndaHr.Model.Text.t | nil,
    :Year => IndaHr.Model.DateTime.t | nil,
    :Link => IndaHr.Model.ResumeLinkLink.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.Publication do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Title, :struct, IndaHr.Model.Title, options)
    |> deserialize(:Description, :struct, IndaHr.Model.Description, options)
    |> deserialize(:DOI, :struct, IndaHr.Model.Text, options)
    |> deserialize(:Link, :struct, IndaHr.Model.ResumeLinkLink, options)
  end
end
