# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.RangeDatetime do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Range
  ]

  @type t :: %__MODULE__{
    :Range => IndaHr.Model.Range1.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.RangeDatetime do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Range, :struct, IndaHr.Model.Range1, options)
  end
end
