# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.RangeModelInt do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :GTE,
    :LTE
  ]

  @type t :: %__MODULE__{
    :GTE => integer(),
    :LTE => integer()
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.RangeModelInt do
  def decode(value, _options) do
    value
  end
end
