# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.Rank do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"CountryRank",
    :"WorldRank"
  ]

  @type t :: %__MODULE__{
    :"CountryRank" => inda_hr.Model.ValueModelConstrainedIntValue.t | nil,
    :"WorldRank" => inda_hr.Model.ValueModelConstrainedIntValue.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.Rank do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"CountryRank", :struct, inda_hr.Model.ValueModelConstrainedIntValue, options)
    |> deserialize(:"WorldRank", :struct, inda_hr.Model.ValueModelConstrainedIntValue, options)
  end
end

