# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.ResumeJobTitleDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"IsValidated",
    :"EntityType",
    :"TextPositions",
    :"RawValue",
    :"Score"
  ]

  @type t :: %__MODULE__{
    :"IsValidated" => boolean() | nil,
    :"EntityType" => String.t | nil,
    :"TextPositions" => [inda_hr.Model.TextPosition.t] | nil,
    :"RawValue" => String.t | nil,
    :"Score" => float() | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.ResumeJobTitleDetails do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"TextPositions", :list, inda_hr.Model.TextPosition, options)
  end
end

