# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.ResumeCommonMinimalData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :JobTitle,
    :PersonalInfo,
    :ContactInfo,
    :PersonLocation
  ]

  @type t :: %__MODULE__{
    :JobTitle => IndaHr.Model.OptionalResumeJobTitle.t | nil,
    :PersonalInfo => IndaHr.Model.PersonalInfo.t | nil,
    :ContactInfo => IndaHr.Model.ResumeContactInfoContactInfo.t | nil,
    :PersonLocation => IndaHr.Model.PersonLocation.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.ResumeCommonMinimalData do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:JobTitle, :struct, IndaHr.Model.OptionalResumeJobTitle, options)
    |> deserialize(:PersonalInfo, :struct, IndaHr.Model.PersonalInfo, options)
    |> deserialize(:ContactInfo, :struct, IndaHr.Model.ResumeContactInfoContactInfo, options)
    |> deserialize(:PersonLocation, :struct, IndaHr.Model.PersonLocation, options)
  end
end
