# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.ResumeRequestsDocument do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"File",
    :"FileExt",
    :"Filename"
  ]

  @type t :: %__MODULE__{
    :"File" => String.t,
    :"FileExt" => String.t,
    :"Filename" => String.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.ResumeRequestsDocument do
  def decode(value, _options) do
    value
  end
end

