# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.ResumeLanguageDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ProficiencyLevel",
    :"LanguageCode",
    :"ProficiencyLevelCode",
    :"IsValidated",
    :"EntityType",
    :"TextPositions",
    :"RawValue",
    :"IsPrimary"
  ]

  @type t :: %__MODULE__{
    :"ProficiencyLevel" => String.t | nil,
    :"LanguageCode" => String.t | nil,
    :"ProficiencyLevelCode" => inda_hr.Model.ProficiencyLevelCode.t | nil,
    :"IsValidated" => boolean() | nil,
    :"EntityType" => String.t | nil,
    :"TextPositions" => [inda_hr.Model.TextPosition.t] | nil,
    :"RawValue" => String.t | nil,
    :"IsPrimary" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.ResumeLanguageDetails do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ProficiencyLevelCode", :struct, inda_hr.Model.ProficiencyLevelCode, options)
    |> deserialize(:"TextPositions", :list, inda_hr.Model.TextPosition, options)
  end
end

