# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.ResumeRemoteWorkingFrequencyRange do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Details,
    :Range
  ]

  @type t :: %__MODULE__{
    :Details => IndaHr.Model.BaseDetails.t | nil,
    :Range => IndaHr.Model.Range.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.ResumeRemoteWorkingFrequencyRange do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Details, :struct, IndaHr.Model.BaseDetails, options)
    |> deserialize(:Range, :struct, IndaHr.Model.Range, options)
  end
end
