# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.ResumeAttachmentsV4 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Pic,
    :CV
  ]

  @type t :: %__MODULE__{
    :Pic => inda_hr.Model.Image.t | nil,
    :CV => inda_hr.Model.ParseResumeDocumentV1.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.ResumeAttachmentsV4 do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Pic, :struct, inda_hr.Model.Image, options)
    |> deserialize(:CV, :struct, inda_hr.Model.ParseResumeDocumentV1, options)
  end
end

