# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.ResumeLinkLink do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :URL,
    :Label
  ]

  @type t :: %__MODULE__{
    :URL => IndaHr.Model.ResumeLinkUrl.t | nil,
    :Label => IndaHr.Model.ResumeLinkLinkLabel.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.ResumeLinkLink do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:URL, :struct, IndaHr.Model.ResumeLinkUrl, options)
    |> deserialize(:Label, :struct, IndaHr.Model.ResumeLinkLinkLabel, options)
  end
end
