# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.ResumeLinkLink do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"URL",
    :"Label"
  ]

  @type t :: %__MODULE__{
    :"URL" => inda_hr.Model.ResumeLinkUrl.t | nil,
    :"Label" => inda_hr.Model.ResumeLinkLinkLabel.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.ResumeLinkLink do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"URL", :struct, inda_hr.Model.ResumeLinkUrl, options)
    |> deserialize(:"Label", :struct, inda_hr.Model.ResumeLinkLinkLabel, options)
  end
end

