# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.ResumeResponsesStatus do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ID,
    :AnalysisStatus,
    :IndexedID
  ]

  @type t :: %__MODULE__{
    :ID => String.t,
    :AnalysisStatus => String.t | nil,
    :IndexedID => String.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.ResumeResponsesStatus do
  def decode(value, _options) do
    value
  end
end
