# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.ResumeEmailAddressEmailAddress do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Address,
    :Label
  ]

  @type t :: %__MODULE__{
    :Address => IndaHr.Model.ResumeEmailAddressAddress.t | nil,
    :Label => IndaHr.Model.ResumeEmailAddressEmailLabel.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.ResumeEmailAddressEmailAddress do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Address, :struct, IndaHr.Model.ResumeEmailAddressAddress, options)
    |> deserialize(:Label, :struct, IndaHr.Model.ResumeEmailAddressEmailLabel, options)
  end
end
