# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.ResumeEmployment do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Code",
    :"Category",
    :"Type",
    :"Industries",
    :"FunctionalAreas"
  ]

  @type t :: %__MODULE__{
    :"Code" => inda_hr.Model.BaseBenefitsValueModelStrictStr.t | nil,
    :"Category" => inda_hr.Model.BaseBenefitsValueModelStrictStr.t | nil,
    :"Type" => inda_hr.Model.EmploymentType.t | nil,
    :"Industries" => [inda_hr.Model.BaseEmploymentsIndustry.t] | nil,
    :"FunctionalAreas" => [inda_hr.Model.BaseBenefitsValueModelStrictStr.t] | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.ResumeEmployment do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Code", :struct, inda_hr.Model.BaseBenefitsValueModelStrictStr, options)
    |> deserialize(:"Category", :struct, inda_hr.Model.BaseBenefitsValueModelStrictStr, options)
    |> deserialize(:"Type", :struct, inda_hr.Model.EmploymentType, options)
    |> deserialize(:"Industries", :list, inda_hr.Model.BaseEmploymentsIndustry, options)
    |> deserialize(:"FunctionalAreas", :list, inda_hr.Model.BaseBenefitsValueModelStrictStr, options)
  end
end

