# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.SearchCreditsRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Info,
    :History
  ]

  @type t :: %__MODULE__{
    :Info => [String.t],
    :History => inda_hr.Model.SemanticHistoryBody.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.SearchCreditsRequest do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:History, :struct, inda_hr.Model.SemanticHistoryBody, options)
  end
end

