# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.Section do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Details,
    :Title,
    :Content
  ]

  @type t :: %__MODULE__{
    :Details => IndaHr.Model.SectionDetails.t | nil,
    :Title => IndaHr.Model.BaseBenefitsValueModelStrictStr.t | nil,
    :Content => IndaHr.Model.BaseBenefitsValueModelStrictStr.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.Section do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Details, :struct, IndaHr.Model.SectionDetails, options)
    |> deserialize(:Title, :struct, IndaHr.Model.BaseBenefitsValueModelStrictStr, options)
    |> deserialize(:Content, :struct, IndaHr.Model.BaseBenefitsValueModelStrictStr, options)
  end
end
