# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.SimilarEntitiesResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Hits,
    :Out
  ]

  @type t :: %__MODULE__{
    :Hits => integer(),
    :Out => [inda_hr.Model.SimilarEntity.t] | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.SimilarEntitiesResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Out, :list, inda_hr.Model.SimilarEntity, options)
  end
end

