# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.SkillComparison do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :OriginSkill,
    :DestinationSkill,
    :Similarity
  ]

  @type t :: %__MODULE__{
    :OriginSkill => String.t | nil,
    :DestinationSkill => String.t | nil,
    :Similarity => float() | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.SkillComparison do
  def decode(value, _options) do
    value
  end
end
