# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.SkillsClassificationResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Skills"
  ]

  @type t :: %__MODULE__{
    :"Skills" => [inda_hr.Model.SkillsResponsesSkill.t]
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.SkillsClassificationResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Skills", :list, inda_hr.Model.SkillsResponsesSkill, options)
  end
end

