# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.SkillComparison do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"OriginSkill",
    :"DestinationSkill",
    :"Similarity"
  ]

  @type t :: %__MODULE__{
    :"OriginSkill" => String.t | nil,
    :"DestinationSkill" => String.t | nil,
    :"Similarity" => float() | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.SkillComparison do
  def decode(value, _options) do
    value
  end
end

