# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.SkillsClassificationRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Skills"
  ]

  @type t :: %__MODULE__{
    :"Skills" => [String.t]
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.SkillsClassificationRequest do
  def decode(value, _options) do
    value
  end
end

