# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.SkillHierarchy do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Level0",
    :"Level1"
  ]

  @type t :: %__MODULE__{
    :"Level0" => [inda_hr.Model.BroaderLevelSkill.t] | nil,
    :"Level1" => [inda_hr.Model.BroaderLevelSkill.t] | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.SkillHierarchy do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Level0", :list, inda_hr.Model.BroaderLevelSkill, options)
    |> deserialize(:"Level1", :list, inda_hr.Model.BroaderLevelSkill, options)
  end
end

