# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.SkillHierarchy do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Level0,
    :Level1
  ]

  @type t :: %__MODULE__{
    :Level0 => [IndaHr.Model.BroaderLevelSkill.t] | nil,
    :Level1 => [IndaHr.Model.BroaderLevelSkill.t] | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.SkillHierarchy do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Level0, :list, IndaHr.Model.BroaderLevelSkill, options)
    |> deserialize(:Level1, :list, IndaHr.Model.BroaderLevelSkill, options)
  end
end
