# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.SkillsClassificationResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Skills
  ]

  @type t :: %__MODULE__{
    :Skills => [IndaHr.Model.SkillsResponsesSkill.t]
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.SkillsClassificationResponse do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Skills, :list, IndaHr.Model.SkillsResponsesSkill, options)
  end
end
