# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.SlimData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"JobTitle",
    :"JobDescription"
  ]

  @type t :: %__MODULE__{
    :"JobTitle" => inda_hr.Model.JobTitleHeader.t,
    :"JobDescription" => inda_hr.Model.JobDescription.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.SlimData do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"JobTitle", :struct, inda_hr.Model.JobTitleHeader, options)
    |> deserialize(:"JobDescription", :struct, inda_hr.Model.JobDescription, options)
  end
end

