# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.SlimJobAdLanguage do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Details,
    :Value
  ]

  @type t :: %__MODULE__{
    :Details => IndaHr.Model.OptionalSlimJobAdLanguageDetails.t | nil,
    :Value => String.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.SlimJobAdLanguage do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Details, :struct, IndaHr.Model.OptionalSlimJobAdLanguageDetails, options)
  end
end
