# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.SlimBaseResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Count,
    :Prices,
    :Detail
  ]

  @type t :: %__MODULE__{
    :Count => integer(),
    :Prices => float() | nil,
    :Detail => [inda_hr.Model.HistoryDetail.t] | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.SlimBaseResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Detail, :list, inda_hr.Model.HistoryDetail, options)
  end
end

