# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.StatsIndex do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Indexname,
    :Stats
  ]

  @type t :: %__MODULE__{
    :Indexname => String.t,
    :Stats => [IndaHr.Model.StatsInfo.t]
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.StatsIndex do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Stats, :list, IndaHr.Model.StatsInfo, options)
  end
end
