# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.StatsInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"DocType",
    :"Count"
  ]

  @type t :: %__MODULE__{
    :"DocType" => String.t,
    :"Count" => integer()
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.StatsInfo do
  def decode(value, _options) do
    value
  end
end

