# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.StatsIndex do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Indexname,
    :Stats
  ]

  @type t :: %__MODULE__{
    :Indexname => String.t,
    :Stats => [inda_hr.Model.StatsInfo.t]
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.StatsIndex do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Stats, :list, inda_hr.Model.StatsInfo, options)
  end
end

