# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.StatsInfo do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :DocType,
    :Count
  ]

  @type t :: %__MODULE__{
    :DocType => String.t,
    :Count => integer()
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.StatsInfo do
  def decode(value, _options) do
    value
  end
end

