# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.StudyAreas do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Area,
    :Degrees
  ]

  @type t :: %__MODULE__{
    :Area => String.t,
    :Degrees => IndaHr.Model.Degrees.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.StudyAreas do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Degrees, :struct, IndaHr.Model.Degrees, options)
  end
end
