# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.StudyAreas do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Area",
    :"Degrees"
  ]

  @type t :: %__MODULE__{
    :"Area" => String.t,
    :"Degrees" => inda_hr.Model.Degrees.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.StudyAreas do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Degrees", :struct, inda_hr.Model.Degrees, options)
  end
end

