# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.SuiteResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Name",
    :"Credits"
  ]

  @type t :: %__MODULE__{
    :"Name" => String.t,
    :"Credits" => float()
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.SuiteResponse do
  def decode(value, _options) do
    value
  end
end

