# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.TextPosition do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Start",
    :"End"
  ]

  @type t :: %__MODULE__{
    :"Start" => integer() | nil,
    :"End" => integer() | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.TextPosition do
  def decode(value, _options) do
    value
  end
end

