# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.TextDetails do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :TextPositions,
    :RawValue
  ]

  @type t :: %__MODULE__{
    :TextPositions => [IndaHr.Model.TextPosition.t] | nil,
    :RawValue => String.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.TextDetails do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:TextPositions, :list, IndaHr.Model.TextPosition, options)
  end
end
