# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.TransitionRecommendationValue do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"DestinationLabel",
    :"DestinationCode",
    :"Similarity",
    :"IsDesirable",
    :"IsSafeDesirable",
    :"IsStrictlySafeDesirable"
  ]

  @type t :: %__MODULE__{
    :"DestinationLabel" => String.t | nil,
    :"DestinationCode" => String.t | nil,
    :"Similarity" => float() | nil,
    :"IsDesirable" => String.t | nil,
    :"IsSafeDesirable" => String.t | nil,
    :"IsStrictlySafeDesirable" => String.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.TransitionRecommendationValue do
  def decode(value, _options) do
    value
  end
end

