# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.TransitionRecommendations do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ESCOClassification,
    :TransitionRecommendation
  ]

  @type t :: %__MODULE__{
    :ESCOClassification => inda_hr.Model.EscoOccupationValue.t | nil,
    :TransitionRecommendation => [inda_hr.Model.TransitionRecommendationValue.t] | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.TransitionRecommendations do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ESCOClassification, :struct, inda_hr.Model.EscoOccupationValue, options)
    |> deserialize(:TransitionRecommendation, :list, inda_hr.Model.TransitionRecommendationValue, options)
  end
end

