# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.UniversityData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Overview,
    :Location,
    :OtherLocations,
    :ContactInfo,
    :Accreditations,
    :Admissions,
    :CarnegieClassification,
    :FacilitiesAndServices,
    :Faculties,
    :MembershipsAndAffiliations,
    :YearlyTuitionRange,
    :SizeAndProfile,
    :StudyAreas,
    :Logo
  ]

  @type t :: %__MODULE__{
    :Overview => inda_hr.Model.Overview.t,
    :Location => inda_hr.Model.UniversityLocationsLocation.t | nil,
    :OtherLocations => [inda_hr.Model.UniversityLocationsLocation.t] | nil,
    :ContactInfo => inda_hr.Model.UniversityContactsContactInfo.t | nil,
    :Accreditations => inda_hr.Model.OptionalAccreditations.t | nil,
    :Admissions => inda_hr.Model.OptionalAdmissions.t | nil,
    :CarnegieClassification => inda_hr.Model.OptionalCarnegieClassification.t | nil,
    :FacilitiesAndServices => inda_hr.Model.OptionalFacilitiesAndServices.t | nil,
    :Faculties => [String.t] | nil,
    :MembershipsAndAffiliations => [String.t] | nil,
    :YearlyTuitionRange => [inda_hr.Model.OptionalTuition.t] | nil,
    :SizeAndProfile => inda_hr.Model.OptionalSizeAndProfile.t | nil,
    :StudyAreas => [inda_hr.Model.StudyAreas.t] | nil,
    :Logo => inda_hr.Model.ValueModelBytes.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.UniversityData do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Overview, :struct, inda_hr.Model.Overview, options)
    |> deserialize(:Location, :struct, inda_hr.Model.UniversityLocationsLocation, options)
    |> deserialize(:OtherLocations, :list, inda_hr.Model.UniversityLocationsLocation, options)
    |> deserialize(:ContactInfo, :struct, inda_hr.Model.UniversityContactsContactInfo, options)
    |> deserialize(:Accreditations, :struct, inda_hr.Model.OptionalAccreditations, options)
    |> deserialize(:Admissions, :struct, inda_hr.Model.OptionalAdmissions, options)
    |> deserialize(:CarnegieClassification, :struct, inda_hr.Model.OptionalCarnegieClassification, options)
    |> deserialize(:FacilitiesAndServices, :struct, inda_hr.Model.OptionalFacilitiesAndServices, options)
    |> deserialize(:YearlyTuitionRange, :list, inda_hr.Model.OptionalTuition, options)
    |> deserialize(:SizeAndProfile, :struct, inda_hr.Model.OptionalSizeAndProfile, options)
    |> deserialize(:StudyAreas, :list, inda_hr.Model.StudyAreas, options)
    |> deserialize(:Logo, :struct, inda_hr.Model.ValueModelBytes, options)
  end
end

