# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.UniversityContactsPhoneNumber do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Number,
    :Label
  ]

  @type t :: %__MODULE__{
    :Number => IndaHr.Model.JobadPhoneNumbersNumber.t | nil,
    :Label => IndaHr.Model.JobadPhoneNumbersPhoneLabel.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.UniversityContactsPhoneNumber do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Number, :struct, IndaHr.Model.JobadPhoneNumbersNumber, options)
    |> deserialize(:Label, :struct, IndaHr.Model.JobadPhoneNumbersPhoneLabel, options)
  end
end
