# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.UniversityAutocompleteResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Term",
    :"Universities"
  ]

  @type t :: %__MODULE__{
    :"Term" => String.t,
    :"Universities" => [inda_hr.Model.UniversityAutocomplete.t]
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.UniversityAutocompleteResponse do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Universities", :list, inda_hr.Model.UniversityAutocomplete, options)
  end
end

