# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.UniversityLocationsLocation do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :City,
    :Country,
    :GeoCoordinates,
    :CountryCode,
    :PostalCode,
    :StreetAddress,
    :County,
    :Region
  ]

  @type t :: %__MODULE__{
    :City => IndaHr.Model.BasePhoneNumbersValueModelStrictStr.t | nil,
    :Country => IndaHr.Model.BasePhoneNumbersValueModelStrictStr.t | nil,
    :GeoCoordinates => IndaHr.Model.ValueModelMongoDbGeoLocation.t | nil,
    :CountryCode => IndaHr.Model.BasePhoneNumbersValueModelStrictStr.t | nil,
    :PostalCode => IndaHr.Model.BasePhoneNumbersValueModelStrictStr.t | nil,
    :StreetAddress => IndaHr.Model.BasePhoneNumbersValueModelStrictStr.t | nil,
    :County => IndaHr.Model.BasePhoneNumbersValueModelStrictStr.t | nil,
    :Region => IndaHr.Model.BasePhoneNumbersValueModelStrictStr.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.UniversityLocationsLocation do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:City, :struct, IndaHr.Model.BasePhoneNumbersValueModelStrictStr, options)
    |> deserialize(:Country, :struct, IndaHr.Model.BasePhoneNumbersValueModelStrictStr, options)
    |> deserialize(:GeoCoordinates, :struct, IndaHr.Model.ValueModelMongoDbGeoLocation, options)
    |> deserialize(:CountryCode, :struct, IndaHr.Model.BasePhoneNumbersValueModelStrictStr, options)
    |> deserialize(:PostalCode, :struct, IndaHr.Model.BasePhoneNumbersValueModelStrictStr, options)
    |> deserialize(:StreetAddress, :struct, IndaHr.Model.BasePhoneNumbersValueModelStrictStr, options)
    |> deserialize(:County, :struct, IndaHr.Model.BasePhoneNumbersValueModelStrictStr, options)
    |> deserialize(:Region, :struct, IndaHr.Model.BasePhoneNumbersValueModelStrictStr, options)
  end
end
