# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.UpdatePicRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Attachments
  ]

  @type t :: %__MODULE__{
    :Attachments => IndaHr.Model.PicAttachmentImage.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.UpdatePicRequest do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Attachments, :struct, IndaHr.Model.PicAttachmentImage, options)
  end
end
