# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.UploadStats do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Count
  ]

  @type t :: %__MODULE__{
    :Count => IndaHr.Model.CountStats.t
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.UploadStats do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Count, :struct, IndaHr.Model.CountStats, options)
  end
end
