# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.UploadStats do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"Count"
  ]

  @type t :: %__MODULE__{
    :"Count" => inda_hr.Model.CountStats.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.UploadStats do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"Count", :struct, inda_hr.Model.CountStats, options)
  end
end

