# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.UpskillingRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :OriginOccupation,
    :TransitionType,
    :Skills
  ]

  @type t :: %__MODULE__{
    :OriginOccupation => String.t,
    :TransitionType => String.t,
    :Skills => [String.t]
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.UpskillingRequest do
  def decode(value, _options) do
    value
  end
end
