# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.Upskilling do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ESCOClassification,
    :TransitionRecommendation,
    :Skills
  ]

  @type t :: %__MODULE__{
    :ESCOClassification => IndaHr.Model.EscoOccupationValue.t | nil,
    :TransitionRecommendation => [IndaHr.Model.TransitionRecommendationValue.t] | nil,
    :Skills => [IndaHr.Model.SlimSkill.t] | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.Upskilling do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ESCOClassification, :struct, IndaHr.Model.EscoOccupationValue, options)
    |> deserialize(:TransitionRecommendation, :list, IndaHr.Model.TransitionRecommendationValue, options)
    |> deserialize(:Skills, :list, IndaHr.Model.SlimSkill, options)
  end
end
