# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.ValidationError do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"loc",
    :"msg",
    :"type"
  ]

  @type t :: %__MODULE__{
    :"loc" => [AnyOfstringinteger],
    :"msg" => String.t,
    :"type" => String.t
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.ValidationError do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"loc", :list, inda_hr.Model.AnyOfstringinteger, options)
  end
end

