# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.WeightedQueryTerm do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Term,
    :Language,
    :Weight
  ]

  @type t :: %__MODULE__{
    :Term => String.t,
    :Language => String.t | nil,
    :Weight => float() | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.WeightedQueryTerm do
  def decode(value, _options) do
    value
  end
end

