# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule IndaHr.Model.WorkExperience do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :Seniority,
    :Duration,
    :PositionTitle,
    :Description,
    :StartDate,
    :EndDate,
    :Ongoing,
    :Location,
    :RemoteWorking,
    :Employer,
    :Industries,
    :Skills,
    :ID
  ]

  @type t :: %__MODULE__{
    :Seniority => IndaHr.Model.BaseSeniority.t | nil,
    :Duration => IndaHr.Model.BaseDuration.t | nil,
    :PositionTitle => IndaHr.Model.OptionalResumeJobTitle.t | nil,
    :Description => IndaHr.Model.Description.t | nil,
    :StartDate => IndaHr.Model.DateTime.t | nil,
    :EndDate => IndaHr.Model.DateTime.t | nil,
    :Ongoing => IndaHr.Model.Ongoing.t | nil,
    :Location => IndaHr.Model.ResumeLocationsLocation.t | nil,
    :RemoteWorking => IndaHr.Model.RemoteWorking.t | nil,
    :Employer => IndaHr.Model.Organization.t | nil,
    :Industries => [IndaHr.Model.ResumeWorkExperiencesIndustry.t] | nil,
    :Skills => [IndaHr.Model.OptionalResumeSkill.t] | nil,
    :ID => String.t | nil
  }
end

defimpl Poison.Decoder, for: IndaHr.Model.WorkExperience do
  import IndaHr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Seniority, :struct, IndaHr.Model.BaseSeniority, options)
    |> deserialize(:Duration, :struct, IndaHr.Model.BaseDuration, options)
    |> deserialize(:PositionTitle, :struct, IndaHr.Model.OptionalResumeJobTitle, options)
    |> deserialize(:Description, :struct, IndaHr.Model.Description, options)
    |> deserialize(:Ongoing, :struct, IndaHr.Model.Ongoing, options)
    |> deserialize(:Location, :struct, IndaHr.Model.ResumeLocationsLocation, options)
    |> deserialize(:RemoteWorking, :struct, IndaHr.Model.RemoteWorking, options)
    |> deserialize(:Employer, :struct, IndaHr.Model.Organization, options)
    |> deserialize(:Industries, :list, IndaHr.Model.ResumeWorkExperiencesIndustry, options)
    |> deserialize(:Skills, :list, IndaHr.Model.OptionalResumeSkill, options)
  end
end
