# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Model.WorkActivityComparisonRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"OriginOccupation",
    :"DestinationOccupation",
    :"ESCOLevel"
  ]

  @type t :: %__MODULE__{
    :"OriginOccupation" => String.t,
    :"DestinationOccupation" => String.t,
    :"ESCOLevel" => integer()
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.WorkActivityComparisonRequest do
  def decode(value, _options) do
    value
  end
end

