# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.WorkExperience do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :Seniority,
    :Duration,
    :PositionTitle,
    :Description,
    :StartDate,
    :EndDate,
    :Ongoing,
    :Location,
    :RemoteWorking,
    :Employer,
    :Industries,
    :Skills,
    :ID
  ]

  @type t :: %__MODULE__{
    :Seniority => inda_hr.Model.BaseSeniority.t | nil,
    :Duration => inda_hr.Model.BaseDuration.t | nil,
    :PositionTitle => inda_hr.Model.OptionalResumeJobTitle.t | nil,
    :Description => inda_hr.Model.Description.t | nil,
    :StartDate => inda_hr.Model.DateTime.t | nil,
    :EndDate => inda_hr.Model.DateTime.t | nil,
    :Ongoing => inda_hr.Model.Ongoing.t | nil,
    :Location => inda_hr.Model.ResumeLocationsLocation.t | nil,
    :RemoteWorking => inda_hr.Model.RemoteWorking.t | nil,
    :Employer => inda_hr.Model.Organization.t | nil,
    :Industries => [inda_hr.Model.ResumeWorkExperiencesIndustry.t] | nil,
    :Skills => [inda_hr.Model.OptionalResumeSkill.t] | nil,
    :ID => String.t | nil
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.WorkExperience do
  import inda_hr.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:Seniority, :struct, inda_hr.Model.BaseSeniority, options)
    |> deserialize(:Duration, :struct, inda_hr.Model.BaseDuration, options)
    |> deserialize(:PositionTitle, :struct, inda_hr.Model.OptionalResumeJobTitle, options)
    |> deserialize(:Description, :struct, inda_hr.Model.Description, options)
    |> deserialize(:Ongoing, :struct, inda_hr.Model.Ongoing, options)
    |> deserialize(:Location, :struct, inda_hr.Model.ResumeLocationsLocation, options)
    |> deserialize(:RemoteWorking, :struct, inda_hr.Model.RemoteWorking, options)
    |> deserialize(:Employer, :struct, inda_hr.Model.Organization, options)
    |> deserialize(:Industries, :list, inda_hr.Model.ResumeWorkExperiencesIndustry, options)
    |> deserialize(:Skills, :list, inda_hr.Model.OptionalResumeSkill, options)
  end
end

