# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Model.Yearoffirstaccreditation do
  @moduledoc """
  Official year of first accreditation.
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: inda_hr.Model.Yearoffirstaccreditation do
  def decode(value, _options) do
    value
  end
end

