# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Api.CreditsManagement do
  @moduledoc """
  API calls for all endpoints tagged `CreditsManagement`.
  """

  alias inda_hr.Connection
  import inda_hr.RequestBuilder

  @doc """
  Search Credits
  Returns the available credits and the history of the API calls already made for the purchased services belonging to *indexname*.  This method will accept an application/json body with optional fields, which allow users to filter or aggregate data according to their needs.  In principle, API call names are the ones shown in this documentation; refer to each method section for additional  details and/or possible changes.

  ### Parameters

  - `connection` (inda_hr.Connection): Connection to server
  - `indexname` (String.t): 
  - `search_credits_request` (SearchCreditsRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, inda_hr.Model.IndexCreditsInfo.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec search_credits_post(Tesla.Env.client, String.t, inda_hr.Model.SearchCreditsRequest.t, keyword()) :: {:ok, inda_hr.Model.IndexCreditsInfo.t} | {:ok, inda_hr.Model.ErrorModel.t} | {:ok, inda_hr.Model.HttpValidationError.t} | {:error, Tesla.Env.t}
  def search_credits_post(connection, indexname, search_credits_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/hr/v2/index/#{indexname}/credits/")
      |> add_param(:body, :body, search_credits_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %inda_hr.Model.IndexCreditsInfo{}},
      {404, %inda_hr.Model.ErrorModel{}},
      {400, %inda_hr.Model.ErrorModel{}},
      {422, %inda_hr.Model.HttpValidationError{}}
    ])
  end
end
