# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule inda_hr.Api.Failures do
  @moduledoc """
  API calls for all endpoints tagged `Failures`.
  """

  alias inda_hr.Connection
  import inda_hr.RequestBuilder


  @doc """
  Get Failures
   This method returns a list of documents that failed to be uploaded to *indexname*.  Note that the optional query parameters (see the schema below) allow to narrow the search to a specific item or import.  Users may also indicate a *doc_type* of interest, and retrieve just the failed documents of that type.   Allowed values for the *doc_type* parameter are: + <code style='color: #333333; opacity: 0.9'>resume</code> for [resumes](https://api.inda.ai/hr/docs/v2/#tag/Resume-Management); + <code style='color: #333333; opacity: 0.9'>job-ad</code> for [job adverts](https://api.inda.ai/hr/docs/v2/#tag/JobAd-Management); + <code style='color: #333333; opacity: 0.9'>application</code> for [applications](https://api.inda.ai/hr/docs/v2/#tag/Application-Management).  

  ## Parameters

  - connection (inda_hr.Connection): Connection to server
  - indexname (String.t): 
  - opts (KeywordList): [optional] Optional parameters
    - :import_id (String.t): 
    - :resume_id (String.t): 
    - :jobad_id (String.t): 
    - :doc_type (String.t): 
  ## Returns

  {:ok, inda_hr.Model.IndexedDocumentFailuresResponse.t} on success
  {:error, Tesla.Env.t} on failure
  """
  @spec get_failures_get(Tesla.Env.client, String.t, keyword()) :: {:ok, inda_hr.Model.IndexedDocumentFailuresResponse.t} | {:ok, inda_hr.Model.ErrorModel.t} | {:ok, inda_hr.Model.HttpValidationError.t} | {:error, Tesla.Env.t}
  def get_failures_get(connection, indexname, opts \\ []) do
    optional_params = %{
      :"import_id" => :query,
      :"resume_id" => :query,
      :"jobad_id" => :query,
      :"doc_type" => :query
    }
    %{}
    |> method(:get)
    |> url("/hr/v2/index/#{indexname}/failures/")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %inda_hr.Model.IndexedDocumentFailuresResponse{}},
      { 404, %inda_hr.Model.ErrorModel{}},
      { 503, %inda_hr.Model.ErrorModel{}},
      { 422, %inda_hr.Model.HttpValidationError{}}
    ])
  end
end
