# NOTE: This file is auto generated by OpenAPI Generator 6.3.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule inda_hr.Api.ResumeToJobAds do
  @moduledoc """
  API calls for all endpoints tagged `ResumeToJobAds`.
  """

  alias inda_hr.Connection
  import inda_hr.RequestBuilder

  @doc """
  Match JobAds Evidence from indexed Resume
  This method can be used for a registered resume; it is analogous to the The [Match JobAds Evidence](https://api.inda.ai/hr/docs/v2/#operation/match_jobads_evidence__POST) method, but it takes in input the ID of the resume instead of its JSON.  Please refer to the [Match JobAds Evidence](https://api.inda.ai/hr/docs/v2/#operation/match_jobads_evidence__POST) description for further details on the method and on its output.

  ### Parameters

  - `connection` (inda_hr.Connection): Connection to server
  - `indexname` (String.t): 
  - `resume_id` (String.t): 
  - `base_jobad_matching_evidence_query` (BaseJobadMatchingEvidenceQuery): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, inda_hr.Model.MatchJobAdEvidenceResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec match_jobads_evidence_from_indexed_resume_post(Tesla.Env.client, String.t, String.t, inda_hr.Model.BaseJobadMatchingEvidenceQuery.t, keyword()) :: {:ok, inda_hr.Model.MatchJobAdEvidenceResponse.t} | {:ok, inda_hr.Model.ErrorModel.t} | {:ok, inda_hr.Model.HttpValidationError.t} | {:error, Tesla.Env.t}
  def match_jobads_evidence_from_indexed_resume_post(connection, indexname, resume_id, base_jobad_matching_evidence_query, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/hr/v2/index/#{indexname}/jobads/matching/resume/#{resume_id}/evidence/")
      |> add_param(:body, :body, base_jobad_matching_evidence_query)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %inda_hr.Model.MatchJobAdEvidenceResponse{}},
      {400, %inda_hr.Model.ErrorModel{}},
      {422, %inda_hr.Model.HttpValidationError{}}
    ])
  end

  @doc """
  Match JobAds Evidence
  This method provides details about the score of a list of job adverts according to the matching with a given resume.  The method should be used after the call of [Match JobAds](https://api.inda.ai/hr/docs/v2/#operation/match_jobads__POST) or [Match JobAds from indexed Resume](https://api.inda.ai/hr/docs/v2/#operation/match_jobads_from_indexed_resume__POST), on a *JobadID* or a set of *JobadID*s returned by one of these methods, in order to obtain the evidence of the matching score.  The relevant information for the matching evidence is the same described in the [Match JobAds](https://api.inda.ai/hr/docs/v2/#operation/match_jobads__POST) method.  For each job advert *ID*, the method returns: + a matching score between the job advert's required and preferred [EQF level](https://en.wikipedia.org/wiki/European_Qualifications_Framework) and the candidate's one (if any); + a matching score between the job advert's required and preferred experience durations and the total duration of the candidate's work experiences (if any); + a matching score between the job advert's required and preferred seniorities and the candidate's seniority (if any); + a detail for each skill in the job advert, containing the relative matching score with respect to the resume; + a detail for each job title in the job advert, containing the relative matching score with respect to the resume.  Each aforementioned matching score has to be considered as an affinity score between job advert's and candidate's data, which contributes to the final [Match JobAds](https://api.inda.ai/hr/docs/v2/#operation/match_jobads__POST) response's <code style='color: #333333; opacity: 0.9'>Score</code>.  Any *JobAdID* not corresponding to an available job advert in the index *indexname* will be ignored.  Note that the [Match JobAds Evidence from indexed Resume](https://api.inda.ai/hr/docs/v2/#operation/match_jobads_evidence_from_indexed_resume__POST), method can be used for a resume which has been already indexed.

  ### Parameters

  - `connection` (inda_hr.Connection): Connection to server
  - `indexname` (String.t): 
  - `jobad_matching_evidence_query` (JobadMatchingEvidenceQuery): 
  - `opts` (keyword): Optional parameters
    - `:src_lang` (String.t): Optional. Language in which the following *Resume.Data* entities are expressed: *Skills*, *WorkExperiences.Skills*, *JobTitles*, *WorkExperiences.PositionTitle* and *Languages*.If missing, the detected *Attachment.CV.PlainText* language is assumed as `src_lang`.

  ### Returns

  - `{:ok, inda_hr.Model.MatchJobAdEvidenceResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec match_jobads_evidence_post(Tesla.Env.client, String.t, inda_hr.Model.JobadMatchingEvidenceQuery.t, keyword()) :: {:ok, inda_hr.Model.MatchJobAdEvidenceResponse.t} | {:ok, inda_hr.Model.ErrorModel.t} | {:ok, inda_hr.Model.HttpValidationError.t} | {:error, Tesla.Env.t}
  def match_jobads_evidence_post(connection, indexname, jobad_matching_evidence_query, opts \\ []) do
    optional_params = %{
      :src_lang => :query
    }

    request =
      %{}
      |> method(:post)
      |> url("/hr/v2/index/#{indexname}/jobads/matching/resume/evidence/")
      |> add_param(:body, :body, jobad_matching_evidence_query)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %inda_hr.Model.MatchJobAdEvidenceResponse{}},
      {400, %inda_hr.Model.ErrorModel{}},
      {422, %inda_hr.Model.HttpValidationError{}}
    ])
  end

  @doc """
  Match JobAds from indexed Resume
  This method performs a search among the job adverts in index *indexname* to find the best matches for a given resume already registered in INDA. To perform the search starting from the resume of a candidate not yet registered in INDA, please use the [Match JobAds](https://api.inda.ai/hr/docs/v2/#operation/match_jobads__POST), method.  The method can be used, for instance, in the career page in order to guide the candidate to the best matching with their resume. The method can also be used -- via scheduled execution over a pool of resumes -- to generate for each applicant a feed of  suggested job positions which are relevant for them, in order to improve candidate engagement.  Skills and job titles are particularly relevant and should be present in the resume to obtain an accurate matching. Other relevant information -- e.g., experience duration, [EQF level](https://en.wikipedia.org/wiki/European_Qualifications_Framework)  -- is retrieved from the resume and contributes to the pertinence score of each job adverts, provided that the index contains a sufficient number of job adverts with that information.

  ### Parameters

  - `connection` (inda_hr.Connection): Connection to server
  - `indexname` (String.t): 
  - `resume_id` (String.t): 
  - `base_jobad_matching_query` (BaseJobadMatchingQuery): 
  - `opts` (keyword): Optional parameters
    - `:size` (integer()): Optional. Number of documents to return.
    - `:offset` (integer()): Optional. Number of documents to skip. Ignored if *cache* is <code style='color: #333333; opacity: 0.9'>true</code>.
    - `:min_score` (float()): Optional. Minimum pertinence score.
    - `:dst_lang` ([String.t]): Results languages. If left empty then the results will not be filtered by language and the they will contain multi-language results.
    - `:jobad_langs` ([String.t]): DEPRECATED: use <code style='color: #333333; opacity: 0.9'>dst_langs</code> instead. Results languages. If left empty then the results will not be filtered by language.

  ### Returns

  - `{:ok, inda_hr.Model.SearchJobAdMatchResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec match_jobads_from_indexed_resume_post(Tesla.Env.client, String.t, String.t, inda_hr.Model.BaseJobadMatchingQuery.t, keyword()) :: {:ok, inda_hr.Model.SearchJobAdMatchResponse.t} | {:ok, inda_hr.Model.ErrorModel.t} | {:ok, inda_hr.Model.HttpValidationError.t} | {:error, Tesla.Env.t}
  def match_jobads_from_indexed_resume_post(connection, indexname, resume_id, base_jobad_matching_query, opts \\ []) do
    optional_params = %{
      :size => :query,
      :offset => :query,
      :min_score => :query,
      :dst_lang => :query,
      :jobad_langs => :query
    }

    request =
      %{}
      |> method(:post)
      |> url("/hr/v2/index/#{indexname}/jobads/matching/resume/#{resume_id}/")
      |> add_param(:body, :body, base_jobad_matching_query)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %inda_hr.Model.SearchJobAdMatchResponse{}},
      {400, %inda_hr.Model.ErrorModel{}},
      {422, %inda_hr.Model.HttpValidationError{}}
    ])
  end

  @doc """
  Match JobAds
  This method performs a search among the job adverts in index *indexname* to find the best matches for a given resume. To perform the search starting from a resume already registered in INDA, we suggest to use the [Match JobAds from indexed Resume](https://api.inda.ai/hr/docs/v2/#operation/match_jobads_from_indexed_resume__POST), method.  The method can be used, for instance, in the career page in order to guide the candidate to the best matching with their resume. The method can also be used -- via scheduled execution over a pool of resumes -- to generate for each candidate a feed of  suggested job positions which are relevant for them, in order to improve candidate engagement.  Skills and job titles are particularly relevant and should be present in the resume to obtain an accurate matching. Other relevant information -- e.g., experience duration, [EQF level](https://en.wikipedia.org/wiki/European_Qualifications_Framework)  -- is retrieved from the resume and contributes to the pertinence score of each job adverts, provided that the index contains a sufficient number of job adverts with that information.  Optionally, a list of [*query filters*](https://api.inda.ai/hr/docs/v2/#tag/Query-Filters) (*QueryFilters*) can be provided to narrow the query. We strongly encourage use of query_filters to reduce computation time and improve the result accuracy.

  ### Parameters

  - `connection` (inda_hr.Connection): Connection to server
  - `indexname` (String.t): 
  - `jobad_matching_query` (JobadMatchingQuery): 
  - `opts` (keyword): Optional parameters
    - `:size` (integer()): Optional. Number of documents to return.
    - `:offset` (integer()): Optional. Number of documents to skip. Ignored if *cache* is <code style='color: #333333; opacity: 0.9'>true</code>.
    - `:min_score` (float()): Optional. Minimum pertinence score.
    - `:src_lang` (String.t): Job Description language. If left empty each section's language will detected automatically.
    - `:dst_lang` ([String.t]): Results languages. If left empty then the results will not be filtered by language and the they will contain multi-language results.
    - `:jobad_langs` ([String.t]): DEPRECATED: use <code style='color: #333333; opacity: 0.9'>dst_langs</code> instead. Results languages. If left empty then the results will not be filtered by language.

  ### Returns

  - `{:ok, inda_hr.Model.SearchJobAdMatchResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec match_jobads_post(Tesla.Env.client, String.t, inda_hr.Model.JobadMatchingQuery.t, keyword()) :: {:ok, inda_hr.Model.SearchJobAdMatchResponse.t} | {:ok, inda_hr.Model.ErrorModel.t} | {:ok, inda_hr.Model.HttpValidationError.t} | {:error, Tesla.Env.t}
  def match_jobads_post(connection, indexname, jobad_matching_query, opts \\ []) do
    optional_params = %{
      :size => :query,
      :offset => :query,
      :min_score => :query,
      :src_lang => :query,
      :dst_lang => :query,
      :jobad_langs => :query
    }

    request =
      %{}
      |> method(:post)
      |> url("/hr/v2/index/#{indexname}/jobads/matching/resume/")
      |> add_param(:body, :body, jobad_matching_query)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %inda_hr.Model.SearchJobAdMatchResponse{}},
      {400, %inda_hr.Model.ErrorModel{}},
      {422, %inda_hr.Model.HttpValidationError{}}
    ])
  end
end
